Arma3/arma3server
https://github.com/dgibbs64/linuxgameservers/issues/251
=> [arma3server] Remove -port flag from parameters, handled by config

DeathmatchClassic/cfg/lgsm-default.cfg, DeathmatchClassic/dmcserver, OpposingForce/cfg/lgsm-default.cfg, OpposingForce/op4server, Ricochet/cfg/lgsm-default.cfg, Ricochet/ricochetserver
This should fix #240 however, I did have problems getting the mods to actually download. Perhaps the problem is related to #274.
=> Added scripts for the rest of the GoldSrc Steam games

OpposingForce/opforserver
https://github.com/dgibbs64/linuxgameservers/commit/44189831c75af2ec636a886bc477610cd2bf9e02#commitcomment-10232019
=> Change "op4" to be a more standard identifier "opfor"

README.md
Already checked and all of them seem to work now.
=> Updated broken wiki links

functions/fn_getopt
Just fixed a little mistake. self explanatory =)
=> Removed duplicate 'backup' parameter (teamspeak3)

7DaysToDie/sdtdserver, functions/fn_stop, functions/fn_validate
Additional code for graceful shutdown of 7 Days to Die and installation of Alloc's Server Fixes mod.
Code per issue #'s 345 & 346.
=> SDTD custom code 

HalfLifeDeathmatchSource/cfg/lgsm-default.cfg, HalfLifeDeathmatchSource/hldmsserver
We recently had a month of Half-Life Deathmatch: Source (the remake of HL1DM, in source engine).  
Here's the results of what I did to make the server
http://store.steampowered.com/app/360/
=> Add Half-Life Deathmatch: Source

functions/fn_functions, functions/fn_getopt, functions/fn_update_functions, functions/fn_update_funtions
This new option will update the functions to the newest version by
simply deleting the contents of the functions dir
=> Added update functions option

functions/fn_monitor, functions/fn_monitor_query
This should fix "monitor" when it's run by a cron job or something like this. (e.g. #318)
Please take a look at it. It works for me. =)
=> Fixed monitoring for cron job

functions/fn_console, functions/fn_install_glibcfix, functions/fn_stop, functions/fn_update_dl, functions/fn_validate
In my last commits I forgot to change the version numbers..
I don't know which date I should choose. Today or 260515?
csgofixes:
If you validate or update the csgo server, a few fixes will be (could be) reset.
There could be a better place for the code.
And btw: the backup command will backup everything in the directory of the script except the backupsdir or am I wrong? Wouldn't it be better if it only backups the gameserver directory + script?
This request just should note these things.
=> CS:GO fixes and corrected dates

Teeworlds/twserver, functions/fn_details, functions/fn_details_config
This is my effort at getting the Teeworlds server started. There's no setup of default config here yet, I'll open a future PR to handle that aspect.
Edit: this is in response to issue #477.
=> Teeworlds server

functions/fn_monitor
=> Fix email notification issue for Teamspeak 3 servers.

Insurgency/cfg/lgsm-default.cfg, Insurgency/insserver
Added tickrate to start-params
added fps_max to config
=> insserver tuning

Insurgency/cfg/lgsm-default.cfg
Ability to adjust lobby size for cooperative gamemodes
=> lobby size

functions/check.sh, functions/check_config.sh, functions/command_details.sh, functions/core_functions.sh, functions/info_config.sh
Check config will check that a config file exists.
=> check_config.sh

GoldenEyeSource/cfg/lgsm-default.cfg, GoldenEyeSource/gesserver
ubuntu 12.04 32bit + GoldenEye_Source_v4.2.4.tar.bz2
=> adding GoldenEye: Source

functions/fix_ins.sh
=> [insserver] fix start/debug

Insurgency/insserver
steam workshop is working with insurgency on linux now
=> insserver workshop support

QuakeLive/cfg/lgsm-default.cfg, QuakeLive/qlserver, QuakeLive/quakeliveserver, functions/install_config.sh
=> adding Quake Live

functions/install_ts3.sh
=> fix ts3 install

functions/update_check.sh
=> TS3 fix : update gets arch the same way as installer

GarrysMod/gmodserver, functions/command_fastdl.sh, functions/core_functions.sh, functions/core_getopt.sh
Working for gmod only right now, will add some other source games soon
=> FastDL first release

functions/command_details.sh, functions/install_ts3.sh
Fixes "not installing the latest version" issue.
Also added missing scriptlogs.
Tested working ;)
Need to pull on development branche once this is merged.
=> matching updater's version checking & fix details

functions/email.sh
=> Removed Executable + Arguments

functions/update_check.sh
Added ability to handle steam branches, needs my other changes to install_serverfiles and gameserverscript as well.
=> Steam branch handling added

ProjectZomboid/pzserver
Added the support to opt in to different branches like iwillbackupmysave. Change in install_serverfiles.sh is also needed to reflect this!
=> Support for branch added

functions/install_serverfiles.sh
Ability to opt in to different branches of a steamgame, e.g. iwillbackupmysave branch from Project Zomboid. To us this you have to add a variable named "branch" to your gameserverscript.
=> Added branch variable

lgsm/functions/command_stop.sh, lgsm/functions/command_validate.sh, lgsm/functions/install_server_files.sh, lgsm/functions/update_dl.sh
=> Dang type-o

lgsm/functions/command_validate.sh, lgsm/functions/install_server_files.sh, lgsm/functions/update_dl.sh
Got the Steam Guard running by removing unbuffer. I tried this with the installer for the terrariaserver. I don't know if this breaks any other installer, but it worked for me.
=> Fix for Steam Guard Authentication, possibly dirty

lgsm/functions/check_deps.sh
Correct the incorrect spelling of dependencies
=> Fix incorrect spelling

EnemyTerritory/cfg/lgsm-default.cfg, EnemyTerritory/etserver, lgsm/functions/command_install.sh, lgsm/functions/info_glibc.sh, lgsm/functions/install_config.sh, lgsm/functions/install_server_files.sh
Hosted Server files on my s3 bucket for now:
- https://s3.amazonaws.com/linuxgsm/enemy-territory.260b.tar.gz
=> adding Enemy Territory

Insurgency/insserver
=> Fixed graceful quit

lgsm/functions/check.sh, lgsm/functions/install_server_files.sh, lgsm/functions/update_steamcmd.sh
Tested working fine for me on Debian 8 x64
Fix for #991
=> Fixes #991

lgsm/functions/command_backup.sh
=> Check variables first & remove lockfile earlier

lgsm/functions/check_steamcmd.sh, lgsm/functions/command_validate.sh, lgsm/functions/install_server_files.sh, lgsm/functions/update_steamcmd.sh
Fixes #1203 
This is branched from develop and merged into develop, versus my other pull request which is a hotfix from the master branch.
https://github.com/GameServerManagers/LinuxGSM/pull/1225
=> Fixes Steam Login fail when password includes a '$'

lgsm/functions/check_deps.sh
=> Refreshes the package list after adding i386 architecture

lgsm/functions/check_deps.sh
=> Adds unzip to required dependencies for LGSM

lgsm/functions/command_details.sh
Fixes #1240
Those needs to be removed from cfg upon merge to master, that's why I made a hotfix rather than a feature.
https://github.com/GameServerManagers/Game-Server-Configs/blob/master/Arma3/server.cfg#L14-L30
=> Fixes Arma3 ports info

ARKSurvivalEvolved/arkserver, Minecraft/mcserver
This isn't urgent because the configs got moved to the right locations anyway.
=> Corrected servercfgdefaults (ARK, Minecraft)

lgsm/functions/install_ts3db.sh
Fix was super simple, but issue is super annoying for ts3server users.
=> [critical] Fixing ts3db prompt's opposite behavior

README.md
Thought this might be kinda useful since we tend to discuss a lot on discord now a days.
I also know that this would make the more annoying people 10x more likely to join the discord and ask noob questions so I'd completely understand if it was denied.
=> Added a discord icon to the readme

ClassicOffensive/coserver, lgsm/functions/install_config.sh, lgsm/functions/install_server_files.sh, lgsm/functions/update_steamcmd.sh
A bit hardcoded, but works fine on my vps.
Required: https://github.com/GameServerManagers/Game-Server-Configs/pull/11
=> Add support for classic offensive

lgsm/functions/fix_ro.sh
=> Added Steam AppID fix for Red Orchestra

lgsm/functions/update_factorio.sh
Renamed updatebranch variable to branch to coincide with the change to the fctrserver.sh variable change in commit 6d5ea2090cf7d65f4485851fa0c2ba66c8f695c7
=> renamed var to branch for continuity with steamCMD

Squad/squadserver, lgsm/functions/command_details.sh, lgsm/functions/command_install.sh, lgsm/functions/core_functions.sh, lgsm/functions/core_getopt.sh, lgsm/functions/info_config.sh, lgsm/functions/install_squad_license.sh
Requesting that @Odinthewanderer also give this a try if possible
=> Add squadserver

lgsm/functions/core_getopt.sh, lgsm/functions/update_mta.sh
Fixes
https://github.com/GameServerManagers/LinuxGSM/issues/1466
=> Fixed MTA not finding the update version

lgsm/functions/check_ip.sh
=> fixed typo/syntax in check_ip.sh

linuxgsm.sh, tests/tests_jc2server.sh, tests/tests_ts3server.sh
That's practically the same structure as the old ones. I can only get it working this way. #1479
So if the main script linuxgsm.sh will be updated, the test scripts should/have to be updated too.
=> Updated Travis test scripts for 170619

lgsm/config-default/config-lgsm/cod2server/_default.cfg, lgsm/config-default/config-lgsm/cod4server/_default.cfg, lgsm/config-default/config-lgsm/codserver/_default.cfg, lgsm/config-default/config-lgsm/codwawserver/_default.cfg
sv_maxclients was not set correctly. There was no maxclients var, only maxplayers.
=> set maxplayers in default for CoD

lgsm/functions/command_wipe.sh
Added Barren map wipe support for RustServer
Enabled script to wipe Barren maps in RustServer
=> Added Barren map Wipe support for RustServers

lgsm/functions/core_messages.sh
Added milliseconds to script logging.
=> Update core_messages.sh to allow logging with milliseconds

lgsm/functions/install_gslt.sh
I also changed the paths in the messages to the full paths to avoid possible confusion with game configs.
Fixes #1599
=> Fixed GSLT installation

lgsm/functions/core_functions.sh
=> Added fix_ark.sh() to core_functions (hotfix/170803.1)

lgsm/data/serverlist.csv
=> Fix serverlist.csv

lgsm/functions/command_stop.sh
- Combined similar graceful stop functions into one
- Added graceful stop support for Project Zomboid (Fixes #1620)
=> Improved graceful shutdown

lgsm/config-default/config-lgsm/gmodserver/_default.cfg
=> Disabled Lua AutoRefresh

lgsm/functions/core_dl.sh, lgsm/functions/install_config.sh, linuxgsm.sh
- fixed forcedl functionality
- forcing download instead of explicitly deleting old server list
- forced game config download otherwise old configs or configs from other games which have the same name like server.cfg will be mistakenly used
=> Repaired and used force download functionality

lgsm/functions/command_start.sh
Reverts GameServerManagers/LinuxGSM#1751
=> Revert "Tmux session size arguments out of order."

lgsm/functions/mods_list.sh
=> Put Oxide for hurtworld grep at right location

lgsm/functions/fix_rust.sh
Fixes #1817 #1813
Tested Working on Debian 9; cannot be worst than nothing for other distro.
=> New fix for Rust

lgsm/functions/command_start.sh, lgsm/functions/install_ts3db.sh
Fixes TS3 install and license acceptation #1806
=> Fix TeamSpeak License acceptation

lgsm/functions/update_factorio.sh
- change log dir to serverfiles dir while issue when mutiple servers installed on the same lgsm dir.
- fix to getting the version.
Signed-off-by: Timo Pollmeier <timo.p@cryz-games.de>
--------------------------------------------------------------------
Fix related on #1854
=> Fix Factorio Updater

lgsm/functions/command_console.sh, lgsm/functions/command_stop.sh
=> Properly attach tmux session

lgsm/functions/mods_list.sh
Fixed PAC3 not being in Global Array
Added Wiremod AutoInstaller
Added Wiremod-Extras AutoInstaller
=> mod_list Update / Fix

lgsm/functions/update_minecraft.sh
=> Reliable way to select latest Minecraft release

lgsm/functions/command_monitor.sh, lgsm/functions/info_config.sh, lgsm/functions/info_messages.sh, lgsm/functions/query_gamedig.sh, lgsm/functions/query_gsquery.py
* Added Query support for Minecraft
* Fixed query enabled display in details
=> Added Query support for Minecraft #1955

lgsm/functions/mods_list.sh
Added support for GOKZ CS:GO server plugin. 
GOKZ is a game mode in CS:GO which involves speedrunning custom maps.
=> added GOKZ to CS:GO server mod options

lgsm/functions/mods_list.sh
I tested it on my (ttt) test server and works fine. Let me know if anyone has a other opinion.
=> Added TTT as CS:GO Gamemode

lgsm/functions/info_messages.sh
CS:GO has game_type and game_mode for example.
=> Add game_type to info_messages.sh

.editorconfig
Feel free to edit this PR to match the conventions used in this repo. I tried to figure out, but maybe somewhere I didn't get right.
=> Create .editorconfig to help coding conventions

lgsm/functions/alert_discord.sh
A lot of people have been getting a "Cannot send an empty message", as their hostname contains characters that weren't JSON-safe (as in you can't literally just throw the variable into a pre-made JSON body and ship it away). 
Since `jq` was made into a forced dependency (which I'm not happy about, since only one game u-), I've decided to put it to good use.
=> Design tweaks and JSON-safe escaping string

lgsm/functions/core_functions.sh, lgsm/functions/fix.sh, lgsm/functions/fix_ts3.sh
=> fix(ts3server): re-add support for libmariadb2

lgsm/functions/update_ts3.sh
=> fix(ts3server): update Teamspeak 3 download mirror #2127

lgsm/functions/info_config.sh
fix queryport for server monitoring the easy way
=> fix(sdtdserver): update queryport for alpha 17

lgsm/functions/command_stop.sh
* feat(stop): update telent message to include port
* fix(stop): sdtd telnet stop will now work with no password set
=>  fix(stop): sdtd telnet stop will now work with no password set

lgsm/config-default/config-lgsm/inssserver/_default.cfg
=> [WIP] Fix Insurgency Sandstorm password bug

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/new-server-request.md, lgsm/functions/info_distro.sh, lgsm/functions/info_messages.sh
Add CPU Info to details
Fixes #2171
=> New details info

lgsm/functions/info_parms.sh, lgsm/functions/query_gamedig.sh, lgsm/functions/query_gsquery.py
Resolves Quake World query issues
fixes #2169
=> fix(qwserver): Quake World query issues

lgsm/functions/install_server_files.sh
=> feat(cod4): update cod4 installer

lgsm/functions/update_ts3.sh
=> feat(ts3server): deprecate legacy ts3 update functions

lgsm/functions/update_factorio.sh
Fixes factorio updating issue
Fixes #2211
=> Fix factorio branching

lgsm/config-default/config-lgsm/kfserver/_default.cfg
=> fix(kfserver): add missing dir variables

lgsm/functions/update_factorio.sh
Removes the factorio tmp dir to resolve patching issues.
Fixes #2228
=> Patch update factorio

lgsm/config-default/config-lgsm/cod2server/_default.cfg, lgsm/config-default/config-lgsm/cod4server/_default.cfg, lgsm/config-default/config-lgsm/codserver/_default.cfg, lgsm/config-default/config-lgsm/coduoserver/_default.cfg, lgsm/config-default/config-lgsm/codwawserver/_default.cfg
=> fix wrong launch parameter for cod games

PULL_REQUEST_TEMPLATE.md
I sometimes correct typos and misspellings. I thought this type could would fit for this.
This type could represent changes not in the actual codebase, rather changes in the comments, printed text, documentation, etc.
=> New type of change in pull request template: small change

lgsm/functions/check_executable.sh
=> fix(check): prevent restart from bypassing check_executable

lgsm/functions/info_config.sh, lgsm/functions/info_messages.sh
Minecraft ports have been corrected.
Fixes #2283
=> fix(mcserver):correct port info

lgsm/config-default/config-lgsm/ndserver/_default.cfg, lgsm/data/serverlist.csv, lgsm/functions/install_config.sh
Have been simulated the entire installation process on local machine, [config file here](https://github.com/GameServerManagers/Game-Server-Configs/pull/49)
Fixes #2290
=> Add Nuclear Dawn

lgsm/functions/core_functions.sh, lgsm/functions/fix.sh, lgsm/functions/fix_terraria.sh
=> fix(terraria): add fix preventing server from starting

lgsm/config-default/config-lgsm/csgoserver/_default.cfg
This new map Sirocco introduced to the game on 2019.04.30.
Plus add note to not use other mapgroups with Danger Zone mode.
```
Co-authored-by: Borzák Attila <1230402+borzaka@users.noreply.github.com>
```
=> Add mapgroup and map example for the new Danger Zone map: Sirocco

PULL_REQUEST_TEMPLATE.md
I often update comments with explanation and examples. The current `Comment update (typo, spelling, etc).` doesn't cover all of these types of changes.
```
Co-authored-by: Borzák Attila <1230402+borzaka@users.noreply.github.com>
```
=> Add more use case for Comment update in PULL_REQUEST_TEMPLATE

lgsm/config-default/config-lgsm/q3server/_default.cfg
Fixes #2331
```
Co-authored-by: Frisa <digimoncn@gmail.com>
```
=> Fix quake 3 launch parameter issue

lgsm/functions/install_server_files.sh
Update Quake World (nQuake) archive.
Fixes #2343
```
```
=>  feat(qwserver): update nquake download archive

lgsm/functions/install_server_files.sh
Update RTCW with latest iortcw binaries
https://drive.google.com/open?id=167mWBBIL_jTNOJszj79cYc8kB8tehq1Z
Fixes #2337
```
```
=> Update RTCW package

lgsm/config-default/config-lgsm/mhserver/_default.cfg, lgsm/functions/info_messages.sh, lgsm/functions/info_parms.sh
=> add new BeaconPort for MORDHAU

lgsm/functions/info_config.sh
Fixes #2335 
```
Co-authored-by: DUDU54 <14166148+DUDU54@users.noreply.github.com>
```
=> fix(mcserver): correct wrong query port fetched from config

lgsm/functions/update_mta.sh
While looking for something, i saw that the name of the executable was not correct
=> fix(mtaserver): wrong executable name in update

lgsm/config-default/config-lgsm/ts3server/_default.cfg
=> fix(ts3server): update ts3 glibc version to new reqirement

lgsm/config-default/config-lgsm/btserver/_default.cfg
Barotrauma now has feature installing dedicated server with steamcmd as an anonymous user.
Use new appid for installing a server without steam auth.
Fixes #2402
```
Co-authored-by: Morbo <14136326+Morb0@users.noreply.github.com>
```
The only workaround for this is to add your details as a co-author. More info about co-authors can be found [here](https://help.github.com/en/articles/creating-a-commit-with-mul …
=> feat(barotrauma): Migrate to use dedicated server appid

lgsm/functions/install_ut2k4_key.sh
Fixes the url of the ut 2004 server key portal to the new url
The url was found here:
https://www.epicgames.com/unrealtournament/forums/past-unreal-tournament-games/unreal-tournament-2003-2004/14811-read-before-posting-most-common-questions-and-useful-links
```
```
=> fix(install): fix url in command

lgsm/functions/command_monitor.sh
=> fix(monitor): fix querydelay

lgsm/config-default/config-lgsm/btserver/_default.cfg
=> fix(btserver): update executable

lgsm/functions/check_deps.sh
Fixes issue with sven co-op due a old dependency
```
```
If documentation does need updating either update it by creating a PR (preferred) or request a …
=> fix(check_deps): sven coop libssl dependency

lgsm/functions/command_debug.sh, lgsm/functions/info_distro.sh, lgsm/functions/info_messages.sh
master server will now only show if set to true
Fixes #2489
```
```
If documentation does need updating either update it by creating a PR (preferred) or request a …
=> fix(details): master server will now only show if set to true

lgsm/functions/command_install_resources_mta.sh
fix(mtaserver): AI no longer waits at a prompt
Fixes #2416
```
Co-authored-by: John Doe <email@example.com>
```
If documentation does need updating either update it by creating a PR (preferred) or request a …
=> fix(mtaserver): AI no longer waits at a prompt

lgsm/config-default/config-lgsm/doiserver/_default.cfg, linuxgsm.sh
=> fix(doiserver): refactor workshop support

lgsm/config-default/config-lgsm/insserver/_default.cfg
Fix following problems for insurgency
1. workshop support
2. change default map to coop map
error message:
>Current playlist "nwi/coop" is incompatible with map "ministry", playlist disabled.
3. change default number of player to 24
> Playlist "nwi/coop" requires maxplayers to be at least 24, attempting to adjust...
maxplayers 24
MATCHMAKING: This playlist requres a maxplayers of at least 24 (clamped to -1). This server will not be eligible for matchmaking.
Fixes #2512
**Thank you for your …
=> fix(insserver): fix various problem

lgsm/config-default/config-lgsm/ts3server/_default.cfg, lgsm/functions/alert.sh, lgsm/functions/command_details.sh, lgsm/functions/command_postdetails.sh, lgsm/functions/info_distro.sh, lgsm/functions/info_messages.sh
=> feat(details): Add game server resource usage and details refactor

lgsm/config-default/config-lgsm/pstbsserver/_default.cfg, lgsm/functions/info_config.sh
=> standardise reservedslots variable

lgsm/functions/command_validate.sh, lgsm/functions/install_server_files.sh, lgsm/functions/update_steamcmd.sh
Accroding steamcmd document, the proper way to designated a branch in steamcmd parameter is "-beta branch" rather than simply put “${branch}" variable in parameter
Fixes #2531
=> Fix branch support

.travis.yml, lgsm/functions/check_deps.sh, lgsm/functions/query_gsquery.py
In centos 8 you must specify which version of python you wanna install
> [root@localhost ~]# yum install mailx postfix curl wget bzip2 gzip unzip python binutils bc jq tmux glibc.i686 libstdc++ libstdc++.i686 libcurl.i686
Extra Packages for Enterprise Linux 8 - x86_64  233 kB/s | 1.9 MB     00:08
Last metadata expiration check: 0:00:01 ago on Fri 04 Oct 2019 12:12:00 AM CST.
Package curl-7.61.1-8.el8.x86_64 is already installed.
Package wget-1.19.5-7.el8_0.1.x86_64 is already installed.
Package bzip2-1.0.6-26.el8.x86_64 is already installed.
Package gzip-1.9-4.el8.x86_64 is already installed.
Package unzip-6.0-41.el8.x86_64 is already installed.
No match for argument: python
There are following alternatives for "python": python2, python36
Package binutils-2.30-49.el8.x86_64 is already …
=> Fix dep checking for Centos8

lgsm/config-default/config-lgsm/wfserver/_default.cfg, lgsm/data/serverlist.csv, lgsm/functions/info_config.sh, lgsm/functions/info_messages.sh, lgsm/functions/info_parms.sh, lgsm/functions/install_config.sh
re-implement warfork based on idtech2 codebase
config file:https://github.com/GameServerManagers/Game-Server-Configs/pull/85
Fixes #2474
=> feat(newserver): warfork

lgsm/functions/info_messages.sh
I realized that I forgot to add slack to the details command output in my completed pull request, this should fix that.
=> bug(alert):include slack alert in detail command

lgsm/functions/info_parms.sh
=> bug(monitor): fix quake2 and query not working

lgsm/functions/command_dev_detect_deps.sh
Add gconf2 detection for dev debug command
is connected to #2551 to detect the libary
=> feat(detect-deps): add gconf2 for dependency checks

lgsm/config-default/config-lgsm/fofserver/_default.cfg
change default number of players to 20 as its the de facto setting for most servers
Fixes #[issue]
=> Update default number of players for FOF

lgsm/functions/check_deps.sh
=> fix(install): pstbs and wurm dependency fix

lgsm/functions/install_server_files.sh
check discord message for download url
Fixes #2568
=> update server file for ZMR

lgsm/config-default/config-lgsm/insserver/_default.cfg
=> add norestart for ins

lgsm/functions/update_ts3.sh
=> fix(ts3server): ts3 version detection when server was started with 'logappend=1' #2584

lgsm/config-default/config-lgsm/rustserver/_default.cfg
Corrected Rust stop mode now set to CTRL+c
Fixes #2580
=> fix(rustserver): corrected stop mode for Rust

.travis.yml
update travis-CI distro to ubuntu 18.04 bionic
Fixes #[issue]
=> feat(travis): update travis-CI distro to ubuntu 18.04 bionic

lgsm/functions/mods_list.sh
=> feat(mod): Update sourcemod to 1.10

lgsm/functions/command_validate.sh, lgsm/functions/install_server_files.sh, lgsm/functions/update_steamcmd.sh
refactor double quote so branch name wont be splitted
=> feat(refactor): double quote for branch name 

lgsm/functions/command_wipe.sh
=> feat(fix): fix typo for rust wipe code

lgsm/config-default/config-lgsm/doiserver/_default.cfg
=> fix(doiserver): resolve server failing to restart without -norestart

lgsm/functions/install_server_files.sh
Non-steam downloads require hosting by LinuxGSM. Certain distros can be sensitive to changes in SSL and have previously prevented downloads working. A new domain `linuxgsm.download` has been created to separate linuxgsm.com and its files. This will ensure that linuxgsm.com can remain fully SSL compliant without accidentally breaking downloads
Fixes #[issue]
=> feat(install): use a new linuxgsm domain linuxgsm.download for files

.travis.yml, lgsm/functions/check_deps.sh
=> fix(install): add code to auto accept steamcmd deb license 

lgsm/functions/check_deps.sh
deprecate centos6 support as no longer supported and tmux source install detection
Fixes #2555 
=> feat(install): deprecate centos6 support and tmux source install detect

lgsm/functions/info_distro.sh
better error catching should ifconfig.co fail to return an ip.
Fixes #2712
=> fix(details): catch error should ifconfig.co fail

lgsm/functions/check_deps.sh, lgsm/functions/command_dev_detect_deps.sh, lgsm/functions/command_dev_detect_ldd.sh
Review of check_dependencies to identify and resolve various issues and incorrect checks
Fixes #2336
=> feat(install): refactor check dependencies

LICENSE
=> Update Licence Date

lgsm/functions/core_legacy.sh, lgsm/functions/info_distro.sh, lgsm/functions/info_stats.sh, linuxgsm.sh
Bugfix language issue where is non-english extra words would appear in stats.
Swapped around event action and event label to make tables more consistent. This will cause some issues with displaying data for a while until all users update.
Fixes #[issue]
=> fix(stats): fix stats bugs with language and sending stats

lgsm/functions/fix_ins.sh, lgsm/functions/fix_mcb.sh, lgsm/functions/fix_onset.sh, lgsm/functions/fix_rw.sh, lgsm/functions/fix_sdtd.sh, lgsm/functions/fix_sof2.sh, lgsm/functions/fix_unt.sh
=> fix(fix): fix sof2 LD_LIBRARY_PATH and standardise usage

lgsm/functions/check_deps.sh
=> change lib32tinfo5 to libtinfo5:i386

lgsm/config-default/config-lgsm/arkserver/_default.cfg, lgsm/functions/check_deps.sh, lgsm/functions/check_steamcmd.sh, lgsm/functions/fix_ark.sh, lgsm/functions/fix_ss3.sh, lgsm/functions/fix_steamcmd.sh
=> Hotfix v20.1.1

lgsm/functions/check_deps.sh
will resolve game servers failing to start if missing dependencies required to run SteamCMD
Fixes #2753
=> fix(steamcmd): failing to start if missing dependencies required to run SteamCMD

lgsm/functions/command_monitor.sh, lgsm/functions/core_messages.sh, lgsm/functions/fix_ark.sh
=> fix(arkserver): resolve further issues highlighted with ark mod fix

lgsm/functions/alert.sh, lgsm/functions/check_deps.sh, lgsm/functions/command_backup.sh, lgsm/functions/command_monitor.sh, lgsm/functions/core_messages.sh
=> fix(messages): fix some messages not using newline correctly

lgsm/functions/alert.sh, lgsm/functions/check_deps.sh, lgsm/functions/command_backup.sh, lgsm/functions/command_monitor.sh, lgsm/functions/core_messages.sh, lgsm/functions/fix_ark.sh, linuxgsm.sh
=> Hotfix v20.1.3

lgsm/functions/check_steamcmd.sh, lgsm/functions/fix_ark.sh
refactor and simplify how ark mods work. After much testing and feedback Ark mods now work as expected using -automanagedmods. 
Fixes #[issue]
=> fix(arkserver): refactor and simplify how ark mods work

lgsm/functions/fix_ark.sh, linuxgsm.sh
=> hotfix v20.1.5

lgsm/functions/check_deps.sh
=> fix(dependency): will not use apt package if Ubuntu 14.04

lgsm/functions/info_config.sh
Have removed the colon replacement, so that ipv6 addresses in first place should also work
Fixes #2658
=> fix(ts3server): improve ts3 ip parsing

lgsm/functions/check_deps.sh, lgsm/functions/command_backup.sh, lgsm/functions/command_validate.sh, lgsm/functions/core_dl.sh, lgsm/functions/fix_ark.sh, lgsm/functions/install_server_files.sh
=> fix(arkserver): remove all appworkshop_346110.acf if multiple exist

lgsm/config-default/config-lgsm/ut3server/_default.cfg, lgsm/functions/info_config.sh, lgsm/functions/info_parms.sh, lgsm/functions/query_gsquery.py
Add ut3 to both gamedig and gsquery monitoring. Update ut3 details command. Add login parameters.
Fixes #2791
=> feat(ut3server): add monitor query and add minor ut3 improvements

lgsm/functions/update_steamcmd.sh, linuxgsm.sh, tests/tests_fctrserver.sh, tests/tests_jc2server.sh, tests/tests_mcserver.sh, tests/tests_ts3server.sh
Hotfix resolve issue with steamcmd update not getting latest remotebuild
=> Hotfix v20.2.1

lgsm/functions/command_backup.sh, lgsm/functions/command_fastdl.sh, lgsm/functions/command_mods_remove.sh, lgsm/functions/command_monitor.sh, lgsm/functions/command_start.sh, lgsm/functions/command_stop.sh, lgsm/functions/core_messages.sh, lgsm/functions/install_logs.sh, lgsm/functions/mods_core.sh
The monitor was counting at fn_sleep_time of 0.5 seconds rather than 1 second. Also noticed a bug with lock file that was creating it with the wrong date format. Added a sleep timer to EOL messages to standardise the time they are displayed.
Fixes #[issue]
=> fix(monitor): fix monitor timings and lockfile bug

lgsm/functions/install_config.sh
Added code to install_config.sh to list out config information on server install. Config files and directories are listed, including a link to the LinuxGSM documentation on game config files.
=> feat(install):Add config locations to install text

lgsm/functions/mods_list.sh
As a server admin i want to have a working mod installation for 7dtd
=> fix(mods): resolve oxide sdtd not functioning correctly

lgsm/functions/update_factorio.sh, lgsm/functions/update_minecraft.sh, lgsm/functions/update_minecraft_bedrock.sh, lgsm/functions/update_mta.sh, lgsm/functions/update_mumble.sh, lgsm/functions/update_steamcmd.sh, lgsm/functions/update_ts3.sh
This fix will ensure that every time an update is found and installed the tmpdir is cleared.
Fixes #2733
=> fix(update): ensure that tmpdir is cleared when update is found

lgsm/functions/info_messages.sh
fixes an if that is wrong
Fixes #2809
=> fix(details): correct if for bf1942

lgsm/functions/update_factorio.sh, lgsm/functions/update_minecraft.sh, lgsm/functions/update_minecraft_bedrock.sh, lgsm/functions/update_mta.sh, lgsm/functions/update_mumble.sh, lgsm/functions/update_steamcmd.sh, lgsm/functions/update_ts3.sh
minor fix preventing update from running on install
=> minor fix preventing update from running on install

lgsm/functions/mods_core.sh
Resolved issue with broken mods downloader
Fixes #2898
=> fix(mods): resolve broken downloader for mods

lgsm/functions/command_start.sh, lgsm/functions/info_distro.sh, lgsm/functions/update_factorio.sh, lgsm/functions/update_minecraft.sh, lgsm/functions/update_minecraft_bedrock.sh, lgsm/functions/update_mta.sh, lgsm/functions/update_mumble.sh, lgsm/functions/update_steamcmd.sh, lgsm/functions/update_ts3.sh
Resolve update on start not working and improve the output to start that the game server has started
Fixes #2897
=> fix(update): fix update on start not working

lgsm/functions/check_ip.sh, lgsm/functions/check_steamcmd.sh, lgsm/functions/command_monitor.sh, lgsm/functions/command_update_linuxgsm.sh, lgsm/functions/core_dl.sh, lgsm/functions/core_legacy.sh
versions of LinuxGSM before v20.3.0 will not use version tags as this can cause LinuxGSM to look for files that do not exist.
Fixes #[issue]
=> fix(update-lgsm) versions before v20.3.0 will not use version tags

lgsm/functions/check_ip.sh, lgsm/functions/check_steamcmd.sh, lgsm/functions/command_monitor.sh, lgsm/functions/command_start.sh, lgsm/functions/command_update_linuxgsm.sh, lgsm/functions/core_dl.sh, lgsm/functions/core_functions.sh, lgsm/functions/core_legacy.sh, lgsm/functions/info_distro.sh, lgsm/functions/mods_core.sh, lgsm/functions/update_factorio.sh, lgsm/functions/update_minecraft.sh, lgsm/functions/update_minecraft_bedrock.sh, lgsm/functions/update_mta.sh, lgsm/functions/update_mumble.sh, lgsm/functions/update_steamcmd.sh, lgsm/functions/update_ts3.sh, linuxgsm.sh, tests/tests_fctrserver.sh, tests/tests_jc2server.sh, tests/tests_mcserver.sh, tests/tests_ts3server.sh
=> Hotfix v20.3.1

lgsm/functions/command_install_resources_mta.sh, lgsm/functions/core_functions.sh, lgsm/functions/fix_mta.sh, lgsm/functions/install_server_files.sh, lgsm/functions/update_minecraft_bedrock.sh, linuxgsm.sh, tests/tests_fctrserver.sh, tests/tests_jc2server.sh, tests/tests_mcserver.sh, tests/tests_ts3server.sh
=> Hotfix v20.3.2

.github/workflows/git-sync.yml, lgsm/functions/core_functions.sh, lgsm/functions/install_server_files.sh, linuxgsm.sh, tests/tests_fctrserver.sh, tests/tests_jc2server.sh, tests/tests_mcserver.sh, tests/tests_ts3server.sh
correct md5sum for ut3server download
Fixes #[issue]
=> Hotfix v20.3.3

lgsm/functions/fix_av.sh
=> fix(avserver): bugfix for postinstall

lgsm/config-default/config-lgsm/bf1942server/_default.cfg, lgsm/config-default/config-lgsm/bfvserver/_default.cfg, lgsm/data/serverlist.csv, lgsm/functions/check_deps.sh, lgsm/functions/core_getopt.sh, lgsm/functions/info_config.sh, lgsm/functions/info_messages.sh, lgsm/functions/install_config.sh, lgsm/functions/install_server_files.sh
Added server support for Battlefield: Vietnam
in the server files provided here: http://linuxgsm.download/BattlefieldVietnam/
recommend deleting the serversettings.con (mods\bfvietnam\settings\serversettings.con) that is inside so the install config function works to pull the default config from the config repo. or could be implemented in a fix. 
I don't have a Centos setup yet to verify the depends.
Fixes #2691
=> feat(new server): Battlefield: Vietnam

lgsm/config-default/config-lgsm/arkserver/_default.cfg
Add support for Epic store players
Fixes #2941 
=> feat(arkserver): add support for epic store players.

lgsm/config-default/config-lgsm/arkserver/_default.cfg
add altsavedirectoryname option to allow custom save location
Fixes #2471
=> feat(arkserver): add altsavedirectoryname option to allow custom save location

lgsm/functions/install_server_files.sh
=> feat(ut2k4server): update release to 3369.3

lgsm/functions/info_distro.sh
gather external ip from ipify.org instead of ifconfig.co
Fixes #2927 
=> fix(info): gather external ip from ipify.org instead of ifconfig.co

lgsm/functions/command_monitor.sh
Resolve hardcoded lock file name
Fixes #2954
=> fix: hard lock reference

lgsm/functions/update_steamcmd.sh
=> fix(update): allow steamcmd to check for update on beta branches

lgsm/functions/info_messages.sh
add appid and branch password to details.
Fixes #2923
=> feat(details): add appid and branch password to details

lgsm/functions/install_server_files.sh
Resolves install boot loop for Soldat.
Fixes #2989
=> fix(solserver): resolve install infinite loop

lgsm/functions/core_functions.sh, lgsm/functions/fix.sh, lgsm/functions/fix_cs.sh, lgsm/functions/fix_hw.sh
The Counter Strike server had a issue starting up, as the file steamclient.so file was missing in the serverfiles.
Fixes #3027
=> fix(csserver): fix missing steamclient.so

lgsm/functions/info_config.sh, lgsm/functions/info_messages.sh
This fixes the config parsing of Factorio and adds a few new infos
Fixes #2987 
=> fix(factorio): fix fetching info from config file

lgsm/functions/core_functions.sh, lgsm/functions/fix.sh, lgsm/functions/fix_cmw.sh, lgsm/functions/fix_cs.sh, lgsm/functions/fix_hw.sh, lgsm/functions/fix_pz.sh, lgsm/functions/fix_steamcmd.sh, lgsm/functions/fix_tu.sh, lgsm/functions/fix_wurm.sh
The Project Zomboid server had a issue starting up, as the file steamclient.so file was missing in the serverfiles.
Fixes #3026
=> fix(pzserver): fix missing steamclient.so

lgsm/config-default/config-lgsm/ecoserver/_default.cfg, lgsm/functions/check_deps.sh, lgsm/functions/info_config.sh, lgsm/functions/info_messages.sh
fixes the start for the ecoserver
Also changes the min glibc version
Adds the needed dependency libgdiplus for the dependency check
Fixes #3023
=> fix(eco): executeable name changed

lgsm/functions/command_wipe.sh
Added custom map wipe support to the command-wipe.sh file 
Changed my previous code to match LinuxGSMs Code.
Fixes #2993
=> feat(rustserver): add rust custom map support

lgsm/functions/info_config.sh
Add Serverpassword and Adminpassword to the details of ARK
Fixes #2778
=> fix(ark): add admin and connect password to details

lgsm/functions/info_config.sh
Fixes the wrong info for the gameserver details and adds configip variable to the info_config
=> fix(eco): display correct values in display and fixup

lgsm/config-default/config-lgsm/squadserver/_default.cfg, lgsm/functions/core_functions.sh, lgsm/functions/fix.sh, lgsm/functions/fix_squad.sh
Move the maindir from Squad to SquadGame
The downside of this change is that the fix needs the diff command, what should be installed usally on any server.
Fixes #2895
=> fix(squad): move systemdir to new location

lgsm/functions/fix_unt.sh
fix steamclient.so startup error 
Fixes #2788
=> fix(untserver): fix steamclient.so issue

lgsm/functions/check_deps.sh, lgsm/functions/info_parms.sh
=> fix(untserver): remove mono-complete requirement and fix query port

lgsm/config-default/config-lgsm/sdtdserver/_default.cfg, lgsm/functions/check_ip.sh, lgsm/functions/command_debug.sh, lgsm/functions/fix_cmw.sh, lgsm/functions/fix_cs.sh, lgsm/functions/fix_hw.sh, lgsm/functions/fix_pz.sh, lgsm/functions/fix_rust.sh, lgsm/functions/fix_sdtd.sh, lgsm/functions/fix_ss3.sh, lgsm/functions/fix_steamcmd.sh, lgsm/functions/fix_tu.sh, lgsm/functions/fix_wurm.sh, lgsm/functions/info_config.sh, lgsm/functions/info_distro.sh, lgsm/functions/info_messages.sh
* Removed logfile parameter to allow console output, this is simular to the change to Rust.
* Removed x86 binary as no longer available
* improved IP handling for telnet and webadmin
* improvements to steamclient.so handling
Fixes #[issue]
=> fix(sdtdserver): fixes to sdtd

lgsm/functions/mods_list.sh
Add the mod Pug for CSGO to the modlist
Fixes #2795
=> feature(mods): add csgo pug to the modlist

lgsm/config-default/config-lgsm/fctrserver/_default.cfg
Adds the parameter to bind the server to a ip address for Factorio
=> fix(fctr): add bind parameter for Factorio server

lgsm/functions/check_deps.sh, lgsm/functions/fix_bo.sh, lgsm/functions/fix_wurm.sh
Fix steamclient.so and dependencys for Wurm Unlimited
The Wurm Server does not need a extra java installed, as there is java included in the serverfiles
Fixes #2652
=> fix(wurm): fix server startup for wurm and dependency

lgsm/functions/mods_list.sh
This refactors the fetch for the get5 mod for sourcemod (csgo)
=> fix(mods): fix csgo get5 fetching for the latest version

lgsm/functions/mods_list.sh
csgo pug fix var not set for mod fetch
Fixes #2795
=> fix(mod): csgo pug fix var not set

lgsm/functions/fix_steamcmd.sh
Fixes insurgency error for the steamclient.so error
from the logfile:
```
S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
```
=> fix(insserver): fix steamclient.so error

lgsm/functions/command_wipe.sh
Includes the player.states.*.db files in the wipe
Fixes #3064
=> fix(rustserver): fix wipe for player.states.*.db

lgsm/functions/command_wipe.sh, lgsm/functions/core_functions.sh, lgsm/functions/fix_steamcmd.sh, lgsm/functions/update_factorio.sh, lgsm/functions/update_minecraft.sh, lgsm/functions/update_minecraft_bedrock.sh, lgsm/functions/update_mta.sh, lgsm/functions/update_mumble.sh, lgsm/functions/update_steamcmd.sh, lgsm/functions/update_ts3.sh, linuxgsm.sh, tests/tests_fctrserver.sh, tests/tests_jc2server.sh, tests/tests_mcserver.sh, tests/tests_ts3server.sh
=> Hotfix v20.5.1

lgsm/functions/info_messages.sh
fix that that is not shown, where the ports need to be edited for Barotrauma
Fixes #3084
=> fix(btserver): add to port edit via config

lgsm/functions/check_deps.sh
Add the missing dependency libicu for Barotrauma
Fixes #3082
=> fix(btserver): add dependency check for libicu

lgsm/functions/install_server_files.sh
Updated Unreal Tournament 99 to the OldUnreal Patch 469a
https://www.oldunreal.com/cgi-bin/yabb2/YaBB.pl?num=1569587267
Fixes #2961
=> feat(ut99server): update UT99 to version 469a (OldUnreal patch)

lgsm/functions/alert_discord.sh, lgsm/functions/alert_ifttt.sh, lgsm/functions/alert_mailgun.sh, lgsm/functions/alert_pushbullet.sh, lgsm/functions/alert_pushover.sh, lgsm/functions/alert_rocketchat.sh, lgsm/functions/alert_slack.sh, lgsm/functions/alert_telegram.sh, lgsm/functions/command_update_linuxgsm.sh, lgsm/functions/core_dl.sh, lgsm/functions/info_distro.sh, lgsm/functions/mods_list.sh, linuxgsm.sh
Change to prevent long connection timeout to prevent long waiting times
fixes #3118 
=> fix: add connect timeout to core curl functions

lgsm/functions/core_functions.sh, lgsm/functions/fix.sh, lgsm/functions/fix_samp.sh, lgsm/functions/install_config.sh
Change rcon password and hostname after installtion, what was not changed after the installation.
Fixes #2999 
=> fix(samp): fix config change after installation

lgsm/functions/core_dl.sh, lgsm/functions/core_functions.sh, lgsm/functions/update_steamcmd.sh, tests/tests_fctrserver.sh, tests/tests_jc2server.sh, tests/tests_mcserver.sh, tests/tests_ts3server.sh
=> Hotfix v20.6.2

lgsm/functions/update_steamcmd.sh
Re does the steamcmd behaviour for the update check for the remote branch
fixes #3140
=> refactor(update): redo steamcmd update part for new behavoir

lgsm/functions/check_deps.sh
Adds the ncurses dependencys for Black Mesa: Death Match
Fixes #3137
=> fix(bmdm): add missing dependency ncurses libs

lgsm/config-default/config-lgsm/mcserver/_default.cfg
Fixes the assignment of the java ram var
Fixes #2540 
=> fix(minecraft): fix java ram assignment

lgsm/functions/check_deps.sh, lgsm/functions/command_skeleton.sh, lgsm/functions/core_functions.sh, lgsm/functions/core_getopt.sh, lgsm/functions/info_messages.sh
A new command that generates a skel directory of empty directories that mirror your game server. This is useful for anyone who wants to backup custom maps and configs to re-apply them later to another server.
Fixes #585
=> feat(skeleton): New command skeleton

lgsm/functions/core_dl.sh
Fixes the infinitive retry when one error is found in the steamcmd log.
Fixes #3157
=> fix(steamcmd): retries are not honored if install succeeds

lgsm/functions/check_config.sh
Refactor of check_config.sh to remove some game-specific code
Fixes #3057
=> feat: refactor check_config removing some game specific code

lgsm/config-default/config-lgsm/gmodserver/_default.cfg
Updates the link to the docs for Garrys Mod wiki link
=> fix(gmod): update link for wiki page

lgsm/functions/core_dl.sh
=> fix(steamcmd): fix branch switch

lgsm/config-default/config-lgsm/vintsserver/_default.cfg, lgsm/data/serverlist.csv, lgsm/functions/check_deps.sh, lgsm/functions/command_update.sh, lgsm/functions/core_functions.sh, lgsm/functions/info_config.sh, lgsm/functions/info_messages.sh, lgsm/functions/install_config.sh, lgsm/functions/install_server_files.sh, lgsm/functions/update_minecraft.sh, lgsm/functions/update_vintagestory.sh
Adds the Vintage Story server
Fixes #3101
=> feat(newserver): Vintage Story

lgsm/config-default/config-lgsm/scpslserver/_default.cfg, lgsm/config-default/config-lgsm/scpslsmserver/_default.cfg, lgsm/data/serverlist.csv, lgsm/functions/check_deps.sh, lgsm/functions/info_config.sh, lgsm/functions/info_messages.sh, lgsm/functions/info_parms.sh, lgsm/functions/install_config.sh
Adds SCP: Secret Laboratory and SCP: Secret Laboratory ServerMod
Fixes #1995
=> feat(newserver): SCP: Secret Laboratory

lgsm/functions/core_steamcmd.sh
Resolves a few shellcheck issues and this is used nowhere
Fixes #3172
=> fix(steamcmd): remove unused parameter

lgsm/functions/command_wipe.sh
Remove all sav files from the folder and remove section that does the same.
Fixes #3176
=> fix(rust): wipe command does not wipe all sav

lgsm/functions/command_dev_detect_deps.sh
Add dependency check for libc++.so.1 in the dev utils
=> feat(dev): add libc++.so.1 for dependency detection

lgsm/functions/check_deps.sh
Add additional dependency for lib `libc++.so.1` for Pavlov VR server 
Fixes #3182
=> fix(pvr): add new dependency

lgsm/config-default/config-lgsm/inssserver/_default.cfg, lgsm/functions/info_config.sh
Insserver does not use a config and only needs the command line parameters.
Fixes #2783
Fixes #3177 
=> fix(inss): fix config to only use parameter

lgsm/functions/core_steamcmd.sh
Fixes that the updateonstart option is working as it should.
Fixes #3166
=> fix(steamcmd): fix update on start not starting the server

lgsm/functions/info_stats.sh
Add support for sendgrid
Fixes #2688 
=> feat(alert): add sendgrid support

lgsm/functions/info_config.sh
Fixes hopefully the servername parsing and simpify the overall parsing for the config.
Fixes #3088
=> fix(ut2k4): better parsing of the serverconfig

lgsm/functions/core_dl.sh, lgsm/functions/core_functions.sh, lgsm/functions/core_github.sh
Add new functions for further refactors and usage for gameservers
=> feat(core): add new functions for github releases

lgsm/config-default/config-lgsm/arma3server/_default.cfg
Fix typo in the arma 3 x64 binary
Fixes #3206 
=> fix(arma3): correct binary name

lgsm/config-default/config-lgsm/vintsserver/_default.cfg
Fix server dir regression from commit c022bfc77926e61af1292e554eef689feed6ff94
=> fix(vints): correct log dir

lgsm/functions/command_backup.sh
* check lockfile has been fixed
* lockfile is only created once compression starts
Fixes #3211
=> fix(backup): resolve issues with lockfile check and creation

lgsm/config-default/config-lgsm/vhserver/_default.cfg, lgsm/functions/info_messages.sh, lgsm/functions/info_parms.sh
=> feat(vhserver): add server query to Valheim

lgsm/config-default/config-lgsm/vhserver/_default.cfg
Add hint to default config file. If password is shorten than 5 characters the server did not start.
=> feat(vhserver): add hint to valheim password length

lgsm/config-default/config-lgsm/vhserver/_default.cfg, lgsm/functions/core_functions.sh, lgsm/functions/info_messages.sh, lgsm/functions/info_parms.sh, linuxgsm.sh, tests/tests_fctrserver.sh, tests/tests_jc2server.sh, tests/tests_mcserver.sh, tests/tests_ts3server.sh
=> Hotfix v21.1.3

lgsm/functions/mods_list.sh
Update Metamod Source stable version
Fixes #3226 
=> fix:(mods): update Metamod:Source stable version

lgsm/functions/command_dev_query_raw.sh, lgsm/functions/command_install_resources_mta.sh, lgsm/functions/command_monitor.sh, lgsm/functions/command_update_linuxgsm.sh, lgsm/functions/core_dl.sh, lgsm/functions/core_functions.sh, lgsm/functions/core_steamcmd.sh, lgsm/functions/info_stats.sh, lgsm/functions/install_config.sh, lgsm/functions/install_modules.sh, lgsm/functions/update_factorio.sh, lgsm/functions/update_jediknight2.sh, lgsm/functions/update_minecraft.sh, lgsm/functions/update_mta.sh, lgsm/functions/update_mumble.sh, lgsm/functions/update_ts3.sh, linuxgsm.sh, tests/tests_fctrserver.sh, tests/tests_jc2server.sh, tests/tests_mcserver.sh, tests/tests_ts3server.sh
Add more hashing methods to the core dl function
This is needed for the future gameservers like papermc and waterfall
=> feature(core_dl): add more hashing methods

lgsm/functions/update_ts3.sh
fix update TS3.
without this changes i can't use update function on my i686 system.
Did not test it on other systems then Debian 10 i686
Fixes #[issue]
=> fix(ts3server): correct arch var in if statement

linuxgsm.sh
Fix a regression with the new startparameter system
=> fix(core): add execution of check_ip before the config init

lgsm/config-default/config-lgsm/pmcserver/_default.cfg, lgsm/config-default/config-lgsm/wmcserver/_default.cfg, lgsm/data/serverlist.csv, lgsm/functions/check_deps.sh, lgsm/functions/check_system_requirements.sh, lgsm/functions/command_update.sh, lgsm/functions/core_functions.sh, lgsm/functions/info_config.sh, lgsm/functions/info_messages.sh, lgsm/functions/install_config.sh, lgsm/functions/install_eula.sh, lgsm/functions/install_server_files.sh, lgsm/functions/update_papermc.sh
PaperMC is a Minecraft server fork of spigot (which is a fork of Bukkit) with some improvement and also an API to check when update is needed
It support version selection via the API
Also did a redesign of the api calls for the download of the jar
PR #2352 and #2354
Thanks @DUDU54 for the inital work for this
=> feat(newserver): add PaperMC Server and Waterfall

lgsm/functions/fix_ts3.sh
Checks and fixes 
Fixes #2513 
=> fix(ts3): add fix to detect accounting file and delete if possible

lgsm/functions/check_deps.sh, lgsm/functions/command_start.sh, lgsm/functions/info_distro.sh, lgsm/functions/info_messages.sh
Remove dependency requirements for ut2k4 and ut99
refactor tmux detection to stop ps forest error with centos 7 
Fixes #2786
=> fix(ut2k4): depricate dependencys for ut2k4 and ut99

lgsm/functions/command_start.sh, lgsm/functions/core_functions.sh, lgsm/functions/core_legacy.sh, lgsm/functions/core_messages.sh, lgsm/functions/fix.sh, lgsm/functions/info_messages.sh, lgsm/functions/install_server_files.sh, linuxgsm.sh
=> fix(config): resolves issue with settings not always picked up in start parameter

linuxgsm.sh
revert part of #3280 to fix upgrade for lgsm
=> fix: revert part of #3280 to fix upgrade

lgsm/functions/info_distro.sh
regression from #3328 for tmux version
=> fix: regression from #3328 for tmux version

lgsm/functions/info_distro.sh
Last backup file not shown correct via the details command
Fixes #3339 
=> fix(details): fix to show last backup

lgsm/functions/install_server_files.sh
=> feat(etl): update ET: Legacy to 2.76

lgsm/functions/install_server_files.sh
=> feat(ut99): update to 469b

lgsm/functions/update_ts3.sh
Fixes the regression from #3283
Fixes #3368
=> fix(ts3): regression from #3283

linuxgsm.sh
fixes the regression from #3315 to reload preexecuteable
Fixes #3373
=> fix(core): fix start paramerter reloading

lgsm/config-default/config-lgsm/arma3server/_default.cfg
=> fix(arma3): increase glibc requirement to 2.27

lgsm/functions/alert_discord.sh
=> fix(alert): correct discord avatar from png to jpg

lgsm/config-default/config-lgsm/rustserver/_default.cfg, lgsm/functions/check_deps.sh
Rust startup can take longer than 5 mins on slower servers. Increased query delay to 10 mins
Fixes #3413 
=> fix(rust): increase rust query delay

lgsm/config-default/config-lgsm/mcbserver/_default.cfg
Make sure gamedig is updated
Add gamedig support for Minecraft Bedrock 
Fixes #3414
=> feat(mcbserver): gamedig is now supported

lgsm/functions/check_deps.sh, lgsm/functions/install_server_files.sh
Fixes #3399, after [the 2.77.1 archive](https://mega.nz/file/Z0ZXhCKb#QRTt1XLi8b933kC5fG1b2anukBziHOA8dWToYUKIhrY) is uploaded to http://linuxgsm.download/WolfensteinEnemyTerritory/etlegacy-v2.77.1-i386-et-260b.tar.xz
No documentation update required.
=> feat(etl): update ET: Legacy to 2.77.1

lgsm/functions/check_deps.sh, lgsm/functions/command_debug.sh, lgsm/functions/command_start.sh, lgsm/functions/core_legacy.sh, lgsm/functions/info_messages.sh, linuxgsm.sh
Resolves issue that causes seed to not correctly be applied
Fixes #3398
=> fix(rust): resolve rust seed not loading to server

lgsm/functions/update_minecraft_bedrock.sh
mcbserver update working again, fixes access denied issues when trying to detect latest build url
Fixes #3505
=> fix(mcb): resolve failing to check remote build

lgsm/functions/check_permissions.sh
Removes erroneous TAB character.
Fixes #3530
=> fix(perms): corrects tab

lgsm/config-default/config-lgsm/mhserver/_default.cfg
Adds the server config to the startparameters
Fixes #2834 
=> fix(mordhau): add config to startparameters

lgsm/config-default/config-lgsm/dodrserver/_default.cfg, lgsm/data/serverlist.csv, lgsm/functions/info_game.sh, lgsm/functions/install_config.sh
Add new server Day of Dragons
Fixes #2572
=> feat(dodr): Day of Dragons

lgsm/config-default/config-lgsm/dodrserver/_default.cfg, lgsm/config-default/config-lgsm/stnserver/_default.cfg, lgsm/data/serverlist.csv, lgsm/functions/info_game.sh, lgsm/functions/info_messages.sh, lgsm/functions/install_config.sh
Add new server Survive the Nights
Fixes #3387
=> feat(newserver): Survive the Nights

lgsm/config-default/config-lgsm/pstbsserver/_default.cfg, lgsm/functions/info_game.sh, lgsm/functions/info_messages.sh
Fixes the servername parsing and make the parsing more simple overall with one sed
Fixes #3472
=> fix(cod4): Improve servername and rcon password parsing

lgsm/functions/check_ip.sh, lgsm/functions/info_distro.sh, tests/tests_jc2server.sh, tests/tests_mcserver.sh
will allow ip command to be used by Slackware users.
Fixes #3570
=> fix(ip): improvements to ip command usage

lgsm/data/almalinux-8.csv, lgsm/data/centos-7.csv, lgsm/data/centos-8.csv, lgsm/data/debian-10.csv, lgsm/data/debian-11.csv, lgsm/data/debian-9.csv, lgsm/data/rhel-7.csv, lgsm/data/rhel-8.csv, lgsm/data/rocky-8.csv, lgsm/data/ubuntu-16.04.csv, lgsm/data/ubuntu-18.04.csv, lgsm/data/ubuntu-20.04.csv, lgsm/data/ubuntu-21.04.csv, lgsm/functions/check_deps.sh, lgsm/functions/command_update_linuxgsm.sh, lgsm/functions/info_distro.sh
Fixes to steamcmd detection.
Corrections to dependency
added checking distro.csv for updates in update-lgsm
Fixes #[issue]
=> fix(install): resolve steamcmd dependency issues

lgsm/functions/core_functions.sh, lgsm/functions/info_game.sh
I added a "sed code" to remove color code from motd
Fixes #3463
=> fix(Minecraft): motd color fix

lgsm/functions/core_functions.sh, lgsm/functions/info_game.sh
This will add info_game functions for sfserver and loserver.
Fixes #3648 
=> fix: add sf & lo to info_game

lgsm/functions/core_functions.sh, lgsm/functions/info_game.sh, lgsm/functions/info_messages.sh
fixed queryport variable 
Fixes #3647
=> fix(unturned): Incorrect query port 

lgsm/functions/core_dl.sh
Fix position of the force_install_dir argument for steamcmd
Fixes #3692 
=> fix(core_dl): fix position of force_install_dir

lgsm/functions/info_game.sh
Fix not executed details for teamspeak 3
Fixes #3681
=> fix(ts3): fix missing details

lgsm/config-default/config-lgsm/sfserver/_default.cfg
Add now needed multihome parameter for Satisfactory server
Fixes #3661
=> fix(sf): add multihome parameter

lgsm/config-default/config-lgsm/colserver/_default.cfg, lgsm/config-default/config-lgsm/dodrserver/_default.cfg, lgsm/config-default/config-lgsm/stnserver/_default.cfg, lgsm/config-default/config-lgsm/vhserver/_default.cfg, lgsm/functions/info_distro.sh
check master server status even if the main port is not used on the steam api
Includes a change for the games that support the new change
=> fix(details): check as well queryport via steam

lgsm/config-default/config-lgsm/cdserver/_default.cfg, lgsm/data/almalinux-8.csv, lgsm/data/centos-7.csv, lgsm/data/centos-8.csv, lgsm/data/debian-10.csv, lgsm/data/debian-11.csv, lgsm/data/debian-9.csv, lgsm/data/rhel-7.csv, lgsm/data/rhel-8.csv, lgsm/data/rocky-8.csv, lgsm/data/serverlist.csv, lgsm/data/ubuntu-16.04.csv, lgsm/data/ubuntu-18.04.csv, lgsm/data/ubuntu-20.04.csv, lgsm/data/ubuntu-21.04.csv, lgsm/functions/info_game.sh, lgsm/functions/info_messages.sh
Add new server "Crafting Dead"
Fixes #3690
=> feat(newserver): Crafting Dead

lgsm/config-default/config-lgsm/squadserver/_default.cfg
=> fix(squad): enable steammaster

lgsm/config-default/config-lgsm/tiserver/_default.cfg, lgsm/data/almalinux-8.csv, lgsm/data/centos-7.csv, lgsm/data/centos-8.csv, lgsm/data/debian-10.csv, lgsm/data/debian-11.csv, lgsm/data/debian-9.csv, lgsm/data/rhel-7.csv, lgsm/data/rhel-8.csv, lgsm/data/rocky-8.csv, lgsm/data/serverlist.csv, lgsm/data/ubuntu-16.04.csv, lgsm/data/ubuntu-18.04.csv, lgsm/data/ubuntu-20.04.csv, lgsm/data/ubuntu-21.04.csv, lgsm/data/ubuntu-21.10.csv, lgsm/data/ubuntu-22.04.csv, lgsm/functions/info_game.sh, lgsm/functions/info_messages.sh, lgsm/functions/install_config.sh
Add new gameserver "The Isle"
Fixes #3715 
=> feat(newserver): The Isle

lgsm/config-default/config-lgsm/pstbsserver/_default.cfg
Enable steammaster for postscriptum server
=> fix(pstbs): enable steammaster

lgsm/functions/fix_steamcmd.sh
fix to symlink the steamclient.so lib for 64 and 32 bit
Fixes #3694 
=> fix(fix_steamcmd): fix to use link for steamclient.so via link

lgsm/functions/install_config.sh
Add config install for Crafting Dead Server
With the latest update the server does not include anymore the config per default.
=> fix(cd): add config install

lgsm/data/debian-10.csv, lgsm/data/debian-11.csv, lgsm/data/debian-9.csv, lgsm/data/ubuntu-18.04.csv, lgsm/data/ubuntu-20.04.csv, lgsm/data/ubuntu-21.04.csv, lgsm/data/ubuntu-21.10.csv, lgsm/data/ubuntu-22.04.csv
fixed partly the issue that the most people do not have it even installed
Fixes #3731
=> fix(deps): add missing dep for distro-info

lgsm/functions/core_dl.sh, linuxgsm.sh
Move the curl check from the module to the main file to be sure it can be used at all.
=> refactor(core): move curl check to main file

lgsm/functions/core_functions.sh, linuxgsm.sh, tests/tests_fctrserver.sh, tests/tests_jc2server.sh, tests/tests_mcserver.sh, tests/tests_ts3server.sh
A special release relating to Docker development allowing different branches to set in environment variables. 
This update is required as by default the master branch version of LinuxGSM is downloaded by default and until this is merged into master it is difficult to develop docker containers using other branches.
=> Release v21.5.1

lgsm/functions/info_game.sh
Fixes the details command for Avorion Server
Fixes #3813
=> fix(av): fix port for config info

lgsm/functions/info_game.sh
fix variable to show the configured queryport via details
Fixes #3823
=> fix(squad): fix variable for queryport

lgsm/data/debian-11.csv
Change to java 17 as there is no java 16 package
Fixes #3822 
=> fix(deps): change openjdk to version 17 for debian 11

lgsm/config-default/config-lgsm/ns2server/_default.cfg
Remove ns2 login 
Fixes #3758 
=> fix(ns2): remove login

lgsm/config-default/config-lgsm/ns2server/_default.cfg
change mod parameter from -mods to -mods2 for ns2
Fixes #3748
=> fix(ns2): change mods commandline

lgsm/functions/mods_list.sh
CSGO Mods: Scraping GOKZ and MovementAPI for latest release version.
Also updated outdated repository url for GOKZ.
=> feat(mods): CSGO Mods - Scrape latest version for GOKZ and MovementAPI

lgsm/config-default/config-lgsm/pc2server/_default.cfg, lgsm/data/serverlist.csv, lgsm/functions/info_game.sh, lgsm/functions/info_messages.sh, lgsm/functions/install_config.sh
=> feat(new server): Project Cars 2

lgsm/config-default/config-lgsm/tfcserver/_default.cfg
Fixes #3858
Fixes TFC default config's "ip" param being set improperly
=> fix(tfcserver): Fix ip flag in _default.cfg

lgsm/functions/update_minecraft_bedrock.sh
Fix renaming the whitelist file to allowlist for MCB
Fixes #3882
=> fix(mcb): fix renaming whitelist to allowlist

lgsm/config-default/config-lgsm/mcbserver/_default.cfg, lgsm/functions/update_minecraft_bedrock.sh
Allows to pin the version for a download to a version.
Either latest or the accurate version of the download is needed here.
Fixes #3879
=> feat(mcb): allow to set hard a version for the server

lgsm/functions/info_game.sh
=> fix(ark): rework parsing of config

lgsm/functions/info_game.sh
Rework Arma3 server config parsing to use sed without grep.
Tested on Ubuntu Focal and CentOS 8.
=> fix(arma3): rework parsing of config

lgsm/config-default/config-lgsm/stserver/_default.cfg
Networking and the server has been rebuild from scratch many commands have been lost and shutdown has changed.
Added:
servername
Modified:
startparameters changed, transfered over commands to new format.
stopmode changed, it needs a quit command now in the console.
Removed:
clearinterval
default.ini got removed, it's now all in setting.xml
Server has been rebuild from scratch commands and dependencies have changed as a result.
Fixes #[issue]
* Dev docs: …
=> fix(st): Networking and server rebuild update

lgsm/functions/install_config.sh, lgsm/functions/install_server_files.sh
Fix the install loop due to a old condition and fix the config install for the server
Fixes #3961
=> fix(bd): install loop due old condition and config

lgsm/data/almalinux-8.csv, lgsm/data/centos-7.csv, lgsm/data/centos-8.csv, lgsm/data/rhel-7.csv, lgsm/data/rhel-8.csv, lgsm/data/rocky-8.csv
Fix regression from commit 490cd3fa5aeadd63180fab5379f49d78748ec8ef
=> fix(deps): remove duplicate dependencys what was added with 490cd3fa5aeadd63180fab5379f49d78748ec8ef

lgsm/functions/info_game.sh
Add version to details output for factorio
Fixes #3675
=> feat(fctr): add function to get the server version via the details command

lgsm/functions/info_game.sh
This changes the order of the variables and some default variables for Vintage Story
Fixes #3658
=> fix(vints): refactor to fix it when there is no config for the server

lgsm/config-default/config-lgsm/squadserver/_default.cfg
Fix to use the proper config for the squad gameserver.
Fixes #3921
=> fix(squad): fix to use the proper default config

lgsm/functions/mods_list.sh
Update sourcemod to the new release 1.11
Fixes #3918
=> feat(mods): update sourcemod to 1.11

lgsm/functions/core_functions.sh, lgsm/functions/fix.sh, lgsm/functions/fix_bt.sh
Fixed could not find a part of the path exception on fresh install Barotrauma server.
Base on `fix_arma3.sh`.
Fixes #3915 
=> fix(bt): missing user data directory

lgsm/functions/check_steamcmd.sh, lgsm/functions/install_server_files.sh
Update CoD4x server files to the latest version to re-activate auto-update
Fixes #3874
=> feat(cod4): update server download to v21.2

lgsm/functions/query_gsquery.py
Fixes regresion from 81998f73c7fcf4ae0155c6cc577f473f0fceed9d
=> fix(query_gsquery): fix regression

lgsm/functions/install_server_files.sh
Fixes #3948
File: https://www.amazon.com/clouddrive/share/RzwCqVtD1zW52yQWOjSHLll5W3uycjIfPX6muSYwJLL
=> fix(zmr): Update to beta 6

lgsm/config-default/config-lgsm/atsserver/_default.cfg, lgsm/config-default/config-lgsm/ets2server/_default.cfg, lgsm/config-default/config-lgsm/rustserver/_default.cfg, lgsm/data/almalinux-8.csv, lgsm/data/almalinux-9.csv, lgsm/data/centos-7.csv, lgsm/data/centos-8.csv, lgsm/data/centos-9.csv, lgsm/data/debian-10.csv, lgsm/data/debian-11.csv, lgsm/data/debian-9.csv, lgsm/data/rhel-7.csv, lgsm/data/rhel-8.csv, lgsm/data/rhel-9.csv, lgsm/data/rocky-8.csv, lgsm/data/rocky-9.csv, lgsm/data/serverlist.csv, lgsm/data/ubuntu-16.04.csv, lgsm/data/ubuntu-18.04.csv, lgsm/data/ubuntu-20.04.csv, lgsm/data/ubuntu-21.04.csv, lgsm/data/ubuntu-21.10.csv, lgsm/data/ubuntu-22.04.csv, lgsm/functions/info_game.sh, lgsm/functions/info_messages.sh, lgsm/functions/install_config.sh
**Branched from feature/ets2**
Adds support for American Truck Simulator
Fixes #4050
-   [ ] New feature (change which adds functionality).
-   [x] New Server (new server added).
-   [x] This pull request Subject follows the Conventional Commits standard.
-   [x] I have provided a detailed …
=> feat(newserver): American Truck Simulator

lgsm/config-default/config-lgsm/ets2server/_default.cfg, lgsm/data/almalinux-8.csv, lgsm/data/almalinux-9.csv, lgsm/data/centos-7.csv, lgsm/data/centos-8.csv, lgsm/data/centos-9.csv, lgsm/data/debian-10.csv, lgsm/data/debian-11.csv, lgsm/data/debian-9.csv, lgsm/data/rhel-7.csv, lgsm/data/rhel-8.csv, lgsm/data/rhel-9.csv, lgsm/data/rocky-8.csv, lgsm/data/rocky-9.csv, lgsm/data/serverlist.csv, lgsm/data/ubuntu-16.04.csv, lgsm/data/ubuntu-18.04.csv, lgsm/data/ubuntu-20.04.csv, lgsm/data/ubuntu-21.04.csv, lgsm/data/ubuntu-21.10.csv, lgsm/data/ubuntu-22.04.csv, lgsm/functions/info_game.sh, lgsm/functions/info_messages.sh, lgsm/functions/install_config.sh
Adds support for Euro Truck Simulator 2
Fixes #4050
-   [ ] New feature (change which adds functionality).
-   [x] New Server (new server added).
-   [x] This pull request Subject follows the Conventional Commits standard.
-   [x] I have provided a detailed with enough description of this …
=> feat(newserver): Euro Truck Simulator 2

lgsm/data/almalinux-8.csv, lgsm/data/almalinux-9.csv, lgsm/data/centos-8.csv, lgsm/data/centos-9.csv, lgsm/data/rhel-8.csv, lgsm/data/rhel-9.csv, lgsm/data/rocky-8.csv, lgsm/data/rocky-9.csv
Bump java version to 17 as it was done for other distros
See as well commit 18833adde1c5cdd19e286670bea97d7715ec26a3
Fixes #4111
-   [x] I have checked that this code is commented …
=> fix(mc): dependencies bump java version to 17 for rhel 8+

.github/labeler.yml, lgsm/config-default/config-lgsm/bt1944server/_default.cfg, lgsm/config-default/config-lgsm/btlserver/_default.cfg, lgsm/data/almalinux-8.csv, lgsm/data/almalinux-9.csv, lgsm/data/centos-7.csv, lgsm/data/centos-8.csv, lgsm/data/centos-9.csv, lgsm/data/debian-10.csv, lgsm/data/debian-11.csv, lgsm/data/debian-9.csv, lgsm/data/rhel-7.csv, lgsm/data/rhel-8.csv, lgsm/data/rhel-9.csv, lgsm/data/rocky-8.csv, lgsm/data/rocky-9.csv, lgsm/data/serverlist.csv, lgsm/data/ubuntu-16.04.csv, lgsm/data/ubuntu-18.04.csv, lgsm/data/ubuntu-20.04.csv, lgsm/data/ubuntu-21.04.csv, lgsm/data/ubuntu-21.10.csv, lgsm/data/ubuntu-22.04.csv, lgsm/functions/info_game.sh, lgsm/functions/info_messages.sh, lgsm/functions/install_config.sh
Renamed Battation 1944 to Battation: Legacy
Fixes #3964
-   [x] I have provided a detailed enough description of this …
=> feat(btl): rename bt1944 to btl

lgsm/functions/mods_list.sh
Fix install of get5 mod
Fixes #4018 
-   [ ] New feature (change which adds functionality).
-   [x] This pull request Subject follows the Conventional Commits standard.
-   [x] I have provided a detailed with enough description of this PR.
-   [x] I …
=> fix(mods): get5 download change to github

lgsm/functions/core_dl.sh
=> fix(core): unhandled curl fail

lgsm/functions/check_ip.sh
=> fix: check localhost ip first on fallback

lgsm/functions/fix.sh
=> refactor(fix.sh): removed error prone code

lgsm/functions/command_sponsor.sh, lgsm/functions/core_functions.sh, lgsm/functions/core_getopt.sh, tests/tests_fctrserver.sh, tests/tests_jc2server.sh, tests/tests_mcserver.sh, tests/tests_ts3server.sh
Convert the word donate to sponsor to bring in line with GitHub Sponsors
Fixes #[issue]
-   [ ] I have provided a …
=> feat: change donate to sponsor

lgsm/functions/update_factorio.sh, lgsm/functions/update_vintagestory.sh
Fixes #[issue]
-   [ ] I have provided a detailed …
=> fix(update): incorrect variable name

lgsm/functions/check.sh, lgsm/functions/command_check_update.sh
Fixes #[issue]
-   [ ] I have provided a detailed …
=> fix(check-update): not getting steamcmd executable for check-update

lgsm/functions/update_factorio.sh, lgsm/functions/update_vintagestory.sh
Fixes variable what gone wrong with https://github.com/GameServerManagers/LinuxGSM/pull/4146 update refactor
superseeds #4178
-   [x] I have checked that this code is commented where …
=> regression(update): fix variable

lgsm/modules/check_ip.sh, lgsm/modules/command_dev_query_raw.sh, lgsm/modules/info_game.sh, lgsm/modules/info_messages.sh, lgsm/modules/query_gamedig.sh, lgsm/modules/query_gsquery.py
use updated gamedig cli method, remove the need to try both --query-port and --port. master server query will try extip first to speed up checks
Fixes #[issue]
-   [x] I have checked …
=> feat: optimise gamedig and master server query

.github/workflows/detals-check-generate-matrix.sh, .github/workflows/serverlist-validate.sh, lgsm/data/serverlist.csv, linuxgsm.sh
To allow ansible and other tools to better use serverlist.csv a header has been added
Fixes #[issue]
-   [ ] I have …
=> feat: add header to serverlist.csv

lgsm/modules/check_executable.sh
This commit adds a temporary fix for upgrading Satisfactory from Update 7 to Update 8. A symlink is created between UnrealServer-Linux-Shipping and UE4Server-Linux-Shipping until the update is released.
Fixes #4241
-   [x] I have …
=> fix(sf): add temporary fix for Satisfactory upgrade

lgsm/modules/info_game.sh
This commit fixedthe way server configurations are parsed by using xmllint to extract values from XML files. 
Fixes #4232
-   [x] I have performed a self-review of my …
=> fix(details): improve xml server config parsing

lgsm/config-default/config-lgsm/tiserver/_default.cfg, lgsm/modules/info_game.sh, lgsm/modules/info_messages.sh
Legacy The Isle is no longer updated and evrima branch is being actively updated. This update fixes and ensures the server will start. 
Note: Epic server system will only display 200 servers on the server list. This is a feature, not a bug. 
Thanks for a "The Isle" community member for help in getting this working.
Fixes #4134 
-   [x] This pull request subject follows the …
=> fix(ti): Update config using evrima branch

lgsm/functions/info_game.sh, lgsm/modules/info_game.sh
Adapts game info to the new specification of server config.
https://community.bistudio.com/wiki/Arma_Reforger:Server_Config
Fixes #4239
-   [x] I have checked that this code is …
=> fix(armar): adapts game info to the new specification of server config

lgsm/config-default/config-lgsm/wurmserver/_default.cfg, lgsm/modules/fix_wurm.sh, lgsm/modules/info_game.sh, lgsm/modules/info_messages.sh
This PR fixes and updates Wurm server to ensure that is works straight after installation. 
Fixes #4265
-   [ ] I …
=> fix: rework wurm server

lgsm/config-default/config-lgsm/pzserver/_default.cfg
Fixes #4255 
Fixes #4256 
-   [x] I have provided …
=> fix(pz): correct start parameters

lgsm/modules/update_mc.sh, lgsm/modules/update_mcb.sh, lgsm/modules/update_mta.sh, lgsm/modules/update_pmc.sh, lgsm/modules/update_vints.sh
[Please include a summary of the change and which issues are fixed.](https://github.com/multitheftauto/mtasa-blue/issues/3176)
Fixes #4308
-   [x] I have checked that this code is …
=> fix(mta): change updater to use builds

lgsm/modules/fix_vh.sh, lgsm/modules/mods_list.sh
Change ValheimPlus repo and adjust fix_vh to remove unstripped_contrib folder and comment out all references in scripts to that directory.
Fixes #4149
-   [x] I have checked that this …
=> fix: Resolve ValheimPlus mod failure to start

lgsm/modules/command_backup.sh
feat(backup): add tmpdir to backup exclusion
Fixes #4381
-   [ ] I have provided a detailed enough description of …
=> feat(backup): add tmpdir to backup exclusion

.github/labeler.yml, lgsm/config-default/config-lgsm/cs2server/_default.cfg, lgsm/modules/info_game.sh
Update parameters and add workshop support. CS2 default config has also been updated
Fixes #[issue]
-   [x] I have …
=> feat(cs2): update parameters and add workshop support

lgsm/modules/info_game.sh, lgsm/modules/mods_list.sh
I did some minor shuffling so that updating Stripper:Source in the future will just be a matter of changing a few things.
Fixes #4473
-   [x] I have checked that this code is commented …
=> chore: update Stripper:Source to latest version

lgsm/modules/check_deps.sh, lgsm/modules/info_game.sh
The generated command to install the missing dependencies was not easy for new users to understand, resulting in those users needing support and asking for help.
-   [x] I have checked …
=> fix(check_deps): clarify to run the generated command as root

lgsm/config-default/config-lgsm/dayzserver/_default.cfg
Switch DayZ server's appid to the stable release
Fixes #4501 
-   [X] New feature (a change which adds functionality).
-   [X] This pull request uses the `develop` branch as its base.
-   [X] This pull request subject follows the Conventional Commits standard.
-   [X] I have performed a self-review of my code.
-   [X] I have checked that this code is commented where required.
-   [X] I have provided a detailed enough description …
=> feat(dayzserver): switch appid to stable release

lgsm/modules/info_distro.sh, lgsm/modules/info_game.sh
Variables where used in if statement before beeing initialized.
Fixes #4465, #4428 
-   [x] I have provided a …
=> [FIX] #4465 lgsm/modules/info_distro.sh: line 100: [: : integer expression expected

lgsm/config-default/config-lgsm/pwserver/_default.cfg
I've implemented the changes suggested by @Crimson-Decoded to support the changed start parameters for Palworld.
Fixes #4514
-   [x] I have checked that this code is commented where …
=> fix(pwserver): fix updated start parameters

lgsm/modules/info_game.sh
This PR fixes an issue where some users experienced very slow LinuxGSM script execution because ip-api.com was not reachable.
This caused the `info_game.sh` script to wait for minutes until curl's default timeout stopped the request: [info_game.sh#L2466](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/modules/info_game.sh#L2466) 
To resolve this issue and enhance the user experience, the following changes have been implemented in this PR:
1. **Timeout Specification:** A timeout of 3 seconds (`curl -s --max-time 3 URL`) has now been explicitly set for connections to ip-api.com. This ensures that if the script cannot establish (and complete) a connection within this period, it will promptly move on to the next steps rather than waiting for curl's default timeout. This change …
=> fix(info_game): add ip query timeout and backup api service

lgsm/config-default/config-lgsm/hzserver/_default.cfg, lgsm/data/almalinux-8.csv, lgsm/data/almalinux-9.csv, lgsm/data/centos-7.csv, lgsm/data/centos-8.csv, lgsm/data/centos-9.csv, lgsm/data/debian-10.csv, lgsm/data/debian-11.csv, lgsm/data/debian-12.csv, lgsm/data/debian-9.csv, lgsm/data/rhel-7.csv, lgsm/data/rhel-8.csv, lgsm/data/rhel-9.csv, lgsm/data/rocky-8.csv, lgsm/data/rocky-9.csv, lgsm/data/serverlist.csv, lgsm/data/ubuntu-16.04.csv, lgsm/data/ubuntu-18.04.csv, lgsm/data/ubuntu-20.04.csv, lgsm/data/ubuntu-22.04.csv, lgsm/data/ubuntu-23.04.csv, lgsm/data/ubuntu-23.10.csv, lgsm/modules/info_game.sh, lgsm/modules/info_messages.sh, lgsm/modules/install_config.sh
Fixes #4515
-   [X] New Server (new server added).
-   [x] I have provided a detailed …
=> feat(new server): humanitz

lgsm/config-default/config-lgsm/wfserver/_default.cfg
As of the latest update on Steam, the installation directory for Linux has been moved out of `Warfork.app/Contents/Resources/`
Issue: #4542 
-   [x] This pull request links to an issue
-   [x] I have provided a …
=> Update Warfork path

lgsm/modules/command_dev_parse_game_details.sh, lgsm/modules/info_distro.sh, lgsm/modules/info_game.sh
I found a small error in the output heading of `./gameserver parse-game-details`
https://github.com/GameServerManagers/LinuxGSM/blob/develop/lgsm/modules/command_dev_parse_game_details.sh#L147
Fixes N/A
-   [x] I have performed a …
=> fix(parse-details): change heading of output & add hint for creating new variables

lgsm/config-default/config-lgsm/pwserver/_default.cfg
Palworld has updated the binary name to PalServer-Linux-Shipping. This PR updates the nsame
Fixes #4550
-   [x] I …
=> fix(vh): update binary name to PalServer-Linux-Shipping

lgsm/data/almalinux-8.csv, lgsm/data/almalinux-9.csv, lgsm/data/centos-7.csv, lgsm/data/centos-8.csv, lgsm/data/centos-9.csv, lgsm/data/debian-10.csv, lgsm/data/debian-11.csv, lgsm/data/debian-12.csv, lgsm/data/debian-9.csv, lgsm/data/rhel-7.csv, lgsm/data/rhel-8.csv, lgsm/data/rhel-9.csv, lgsm/data/rocky-8.csv, lgsm/data/rocky-9.csv, lgsm/data/serverlist.csv, lgsm/data/ubuntu-16.04.csv, lgsm/data/ubuntu-18.04.csv, lgsm/data/ubuntu-20.04.csv, lgsm/data/ubuntu-22.04.csv, lgsm/data/ubuntu-23.04.csv, lgsm/data/ubuntu-23.10.csv, lgsm/data/ubuntu-24.04.csv, lgsm/modules/info_game.sh, lgsm/modules/info_messages.sh, lgsm/modules/install_config.sh
Fixes #4499
-   [x] I have provided a detailed …
=> feat: deprecate Memories of Mars

lgsm/modules/command_dev_parse_game_details.sh, lgsm/modules/info_game.sh
fix missing serverpassword detail in cs2 and fix rconpassword
Fixes #4447
-   [x] I have provided a detailed enough …
=> fix missing serverpassword detail

lgsm/config-default/config-lgsm/ut3server/_default.cfg, lgsm/modules/install_server_files.sh
Fixes #4656
-   [ ] I have provided a detailed …
=> feat(ut3): Update the UT3 archive to have OpenSpy fix

lgsm/data/serverlist.csv
Upgrade docker containers to Ubuntu 24.04
Fixes #4670
-   [x] I have provided a detailed enough description of this …
=> feat: upgrade docker containers to ubuntu 24.04
