GameServerManagers/LinuxGSM

GarrysMod/cfg/lgsm-default.cfg
GarrysMod/gmodserver

Adding a variable near the top of gmodserver to set the garry's mod gamemode, as well as fixed a few outdated/removed server variables in the default config
Wasn't sure if you wanted to keep all the source server scripts the same or not, but this'd be a really useful feature for anyone running garry's mod servers, nice and easy changing of their gamemode

Added gamemode variable for gmodserver

---

GarrysMod/gmodserver

It is possible to have maps in the gamemodes folder in that case its a requirement for the game to know the gamemode is before it can change to a map.
If srcds can not find the map it will refuse to start.

gamemode before map

---

functions/fn_update_check

Now Versions are sorted against Name.
Bug: The update was installing v3.0.3 over my v3.0.11.2!
```
./ts3server update
[  OK  ] Update ts3-server: Checking for update: teamspeak.com
Update available:
Current build: 3.0.11.2
Available build: 3.0.3
Applying update...
[...]
```

fix: TS3 Version check

---

functions/fn_start

Fixed an 'else' that belonged to the wrong 'if block'. Introduced with 2799224afa8b75be71dde30e0a9d9e96c7e9fc51
When you start the server (when it was stopped) there won't be the OK message.
I think this 'else' shouldn't be there?

fixed wrong else position

---

Left4Dead/l4dserver
functions/fn_console
functions/fn_install_glibcfix
functions/fn_stop

**Fixed 'Unknown command "servercfgfile"'** ( #230 )
Just removed it because it doesn't exists in L4D1.
**Fixed Steam / LAN error** ( #230 | #311 )
This fixes the error message in console but I'm not sure about the ingame problem because I don't have this game to check it.
**Added default input "y" when opening console** ( #395 )
I think this is the easiest way to implement it but it requires bash v4. I don't know if it is a problem.
**Added lock file removal for all servers**
I think it wasn't intended to be missing?

A few fixes and additions

---

functions/fn_details_distro

Using lxc (Linux Containers) 1.0.3, with Ubuntu 14.04 x64 as host and guest.
In the host, /proc/uptime looks like "22821.86 178565.50". In the guest, "11752 0". This patch adds support for both.

Fixed parsing uptime when it has no decimal point

---

functions/fn_stop

Removed "inifile=${ini}" parameter from fn_stop_teamspeak3 since ts3server_startscript.sh stop doesn't handle parameters.

Removed parameters from TeamSpeak 3

---

functions/fn_email

The bracket was apparently accidently removed in e943e24e304927e88c1f966723c1c55fbdd513cb .

Added missing bracket and linebreak

---

ProjectZomboid/pzserver

Attempt to fix issue #485. I've tested this on a VM, but if anyone else is able to test, it'd be appreciated.
The Project Zomboid AppID has changed as well as the structure of its
server files. This commit should point the scripts to the appropriate
files.

Update ProjectZomboid AppID, fix server file

---

Terraria/cfg/lgsm-default.txt
Terraria/terrariaserver
functions/fn_details
functions/fn_details_config
functions/fn_install_config

Updated pull request #494 from master then merged back in to master

Merging Pull request #494

---

functions/fn_content_gmod
functions/fn_functions
functions/fn_getopt

Merging this to work in to master

gmod-content-mounting

---

functions/fn_details

The function was not working properly since the pid variable is missing.
This solve the issue.

Fix fn_details_statusbottom in fn_details_source()

---

Arma3/arma3server
Arma3/cfg/lgsm-default.server.cfg
functions/fn_details_config

added parameters. descriptions taken from: https://community.bistudio.com/wiki/Arma_3_Startup_Parameters
-servermod
Loads the specified sub-folders for different server-side (not broadcasted to clients) mods. Separated by semi-colons. Absolute path and multiple stacked folders are possible. 
-autoinit:
Automatically initialize mission just like first client does. Note: Server config file (server.cfg) must contain Persistent=1; , if it's 0 autoInit skips. 
-loadmissiontomemory: 
Server will load mission into memory on first client downloading it. Then it keeps it pre-processed pre-cached in memory for next clients, saving some server CPU cycles

enhanced mod-support

---

functions/check_ip.sh

Not having the line break makes it a bit harder than just double-clicking to select the url and copy/paste it.

Line break at end of IP warning

---

functions/logs.sh

fixes #354 
Took me some time to figure out how it was working, and to simplify it a little bit (with the exact same functionalities), but i think it's way cleaner that way.
Tested, working on one of my DarkRP.
I see no reason why it wouldn't work for sourcemod, as the folder path is right, and i triple checked the syntax.

Logfiles cleaning

---

functions/update_check.sh

Simplifying TS3 update checking using "sort" as its best to sort version numbers without the need of removing dots and outputting the file himself.
Magic command is : cat .ts3_version_numbers_unsorted.tmp | sort -r --version-sort -o .ts3_version_numbers_sorted.tmp
Fixes #694

Fixing ts3 update checking

---

functions/check_deps.sh

In the end, i went for checking that a mail server is here in any case.
Before the last commit, it wouldn't check packages as long as a mailx folder was detected, which wasn't very clean.

Accept two main other mail servers

---

Rust/rustserver

Can't test it out as multiple server instances don't work and my server now has players on it, but if that looks OK to you, it should be fine.

conditional server.seed and comments rework

---

GarrysMod/gmodserver

Fixes https://github.com/dgibbs64/linuxgsm/issues/685
Tickrate needs to be lowered in order to be able to handle a large amount of players.
Default tickrate is 66.66, but the -tickrate commnand will round numbers to the lower integer. So i'll default at 66 and not -the more accurate- 67 to not worry anyone with a "non standard" value.
For the +r_hunkalloclightmaps 0, it fixes the hunk overflow crash on server startup when using maps with too much lights (and there are a lot of them). It changes the way lights are stored in RAM, the 0 mode (default one a few years ago, and still default one on clients) can handle a way larger amount of lights, but a theoretically a bit slower way. I noticed no difference, so it's a good thing to fix it by default.

Gmod tickrate and fix for many maps

---

functions/command_ts3_server_pass.sh

Even if we answer no to the "Continue?"-Question the script will stop and start the server.
It will only skip the enter new password part.
```
fetching functions/command_ts3_server_pass.sh...OK
Teamspeak 3 ServerAdmin Password Change
============================
Press "CTRL+b d" to exit console.
Info! You are about to change the Teamspeak 3 ServerAdmin password.
Warning! Teamspeak 3 will restart during this process.
Continue? [y/N]n
Exiting
[ INFO ] Change password ts3-server: Applying new password
fetching functions/command_stop.sh...OK
fetching functions/check_deps.sh...OK
[  OK  ] Stopping ts3-server: Teamspeak 3 Server
[ INFO ] Change password ts3-server: Starting server with new password
fetching functions/command_start.sh...OK
fetching functions/check_tmux.sh...OK
fetching …
```

TS3 change password "No" answer is ignored

---

functions/command_start.sh
functions/command_ts3_server_pass.sh

Always start the server with inifile parameter to ensure right settings.
And reset the ts3serverpass variable so it won't restart the server again in new password mode.

Fix more TS3 change password related issues

---

lgsm/functions/command_stop.sh

fn_stop_graceful_source() didn't call fn_stop_tmux() or ' rm -f "${rootdir}/${lockselfname}" '. That's why monitoring restarted the server when it was shutdown gratefully.

Fixed lock file removal for source servers

---

ARKSurvivalEvolved/arkserver
BrainBread2/bb2server
lgsm/functions/check_deps.sh
lgsm/functions/command_details.sh
lgsm/functions/command_fastdl.sh
lgsm/functions/fix_ins.sh
lgsm/functions/update_check.sh

Ref #844 and the original pull request #770 from @yadutaf
Ark does not seem to honor parameters in GameUserSettings.ini.  This change sets them in the script instead, where it does affect the actual runtime game parameters (QueryPort, for example).
Setting the parameters in the script then also addresses another unresolved issue in the ./arkserver details" output - which currently fails because arkserver's engine isn't aligned with either selfname or configfile paradigm in command_details.sh
Declaring the game parameters in the script allows arserver to fall in the ${selfname} category for parameters in the details command.  Looking at the scripts, Ark seems to be the only unreal4 engine, so it (unreal4) was added to the corresponding ports_edit_array for those games that fall under the …

Ark server updates to enable the details command

---

CounterStrikeGlobalOffensive/csgoserver

To avoid possible confusion like in #900. The old order encouraged the mix up of "gametype" and "gamemode".

Changed the order of game mode variables

---

lgsm/functions/command_stop.sh

Cleans up any non-digit returned in the resulting process id query when the process has terminated.
In the event the process id vanishes, the "let" command in the subsequent line sets the value to 0 (which was the intended result when no process id was found).

Fixing the issue when the process id vanishes.

---

Rust/rustserver

Some of the map settings have different ranges or they've changed in recent updates to Rust. I've cleaned up the settings and adjusted the comments as required.

Comment and default map settings cleanup.

---

lgsm/functions/command_details.sh

Show Pushbullet with Email alert under Script Details

Update: command_details.sh - Show Pushbullet alert

---

lgsm/functions/info_config.sh

The info_config part of the 7 Days to Die support was missing.
May fix issue #880

Add support to 7 days to die to info_config.sh

---

lgsm/functions/check_config.sh

If no RCON password is set, it completely messes up with Rust.
If the default password is set, the admin should be warned as it's quite dangerous.
Tested: working as expected.
Fixes #848

RCON password check for Rust

---

lgsm/functions/check.sh
lgsm/functions/check_system_requirements.sh
lgsm/functions/core_functions.sh
lgsm/functions/info_distro.sh

Added what we need to check system requirements, starting with RAM.
It will check RAM upon server install and start, and display a warning if not enough RAM is detected.
For now, only Rust has a RAM requirement set at 4000MB RAM.
It's now easy to add other games, or even HDD space check before server installation.
#847

System requirements

---

lgsm/functions/check_permissions.sh

Fixes the error message when doing a fresh install.
e.g.:
```
~$ ./pzserver install
fetching core_dl.sh...OK
fetching core_functions.sh...OK
fetching core_trap.sh...OK
fetching core_messages.sh...OK
fetching core_getopt.sh...OK
fetching command_install.sh...OK
fetching check.sh...OK
fetching check_root.sh...OK
fetching check_permissions.sh...OK
find: ‘/home/pzserver/serverfiles’: No such file or directory
fetching check_glibc.sh...OK
fetching info_glibc.sh...OK
fetching info_distro.sh...OK
fetching check_tmux.sh...OK
fetching install_header.sh...OK
```
**Is there a reason to use**
`if [ -n "${functionsdir}" ]; then`
**over**
`if [ -d "${functionsdir}" ]; then`
**?** ([source](https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/check_permissions.sh#L26))
-n just checks if the …

Added directory check

---

lgsm/functions/gsquery.py

"A prefix of 'b' or 'B' is ignored in Python 2; it indicates that the literal should become a bytes literal in Python 3 (e.g. when code is automatically converted with 2to3). A 'u' or 'b' prefix may be followed by an 'r' prefix."
"Bytes literals are always prefixed with 'b' or 'B'; they produce an instance of the bytes type instead of the str type. They may only contain ASCII characters; bytes with a numeric value of 128 or greater must be expressed with escapes."
Fixes https://github.com/dgibbs64/linuxgsm/issues/964

Compatibility with python 3.x

---

CounterStrikeGlobalOffensive/csgoserver
GarrysMod/gmodserver
NaturalSelection2/ns2server
lgsm/functions/command_validate.sh
lgsm/functions/install_server_files.sh
lgsm/functions/update_steamcmd.sh

I noticed that there was already a parameter to opt into a steam app branch. However given parameter wasn't used in most methods. 
I fixed this and added the parameter to the game scripts of games which I sometimes host on non default branches.
Various developers use steam branches in various ways, so this feature might be not used by many server operators. However it's certainly nice to have.
I tested this change with the give game server apps (4940, 740 and 4020).

Fix the steam branch parameter

---

lgsm/functions/check_deps.sh

Fixes by adding more required dependencies to CS:S and GMod:
```
WARNING: Failed to load 32-bit libtinfo.so.5 or libncurses.so.5.
Please install (lib32tinfo5 / ncurses-libs.i686 / equivalent) to enable readline.
```
This enables the access of previous commands with the arrow keys
Like in #212 
**There are maybe more (source) games with this warning.**

Added required dependencies to enable readline

---

TeamSpeak3/cfg/lgsm-default.ini

IPv6 support was added to TeamSpeak 3 server version 3.0.13. It's also possible to use IPv6 addresses in the query_ip_whitelist.txt, query_ip_blacklist.txt and tsdns_settings.ini. Please note, that you need to set the IPv6 inside square brackets in the tsdns_settings.ini (and only there) like this: ipv6-ts3.example.com=[2606:2800:220:1:248:1893:25c8:1946]:9987

Added IPv6 bindings for TeamSpeak 3 server 3.0.13 and newer

---

ARKSurvivalEvolved/arkserver

In ZSH if you don't wrap the params from ARK in ```" ``` the tmux session won't start.
Tested and still working fine with bash.

Fix ARK params for ZSH

---

lgsm/functions/command_fastdl.sh

This commit should fix the issue with Bug #1049 not Commiting graph
files for maps to the FastDL server by searching for files with the .ain
extension.

Fix for Bug #1049

---

NaturalSelection2/ns2server

The log dir is used by Natural Selection 2 to store various logs: e.g. console logs, performance logs or luajit tracert logs.

Added missing logdir start parameter for Natural Selection 2 

---

lgsm/functions/info_config.sh

Adding -0 to xargs to prevent it from interpreting single quotes (in servername variables, for example).
Ref: #1111

Adjusting xargs' interpretation of single quotes: ref #1111

---

lgsm/functions/update_factorio.sh

(I know there is already a pull request for Factorio #1072, but I wasn't sure how to merge my code to it)
Took me a while but here is a working version of Factorio headless server support! It fetches the server from Factorio.com, sets the config and all that. 
Factorio/fctrserver has reference to my Github repo, but just change that and it should work fine :)

Factorio headless support

---

ProjectZomboid/pzserver
lgsm/functions/install_config.sh

- Corrected default config names
- Use service name for config and "server name"
- Added fn_check_cfgdir call to create non-existing config directory
Fixes #1190

[master] Fixed Project Zomboid config handling

---

7DaysToDie/sdtdserver
Arma3/arma3server
BladeSymphony/bsserver
BrainBread2/bb2server
KillingFloor/kfserver
NS2Combat/ns2cserver
NaturalSelection2/ns2server
RedOrchestra/roserver
Ricochet/ricochetserver
Starbound/sbserver
Teeworlds/twserver
Terraria/terrariaserver
lgsm/functions/check_steamcmd.sh
lgsm/functions/command_validate.sh
lgsm/functions/install_server_files.sh
lgsm/functions/update_steamcmd.sh

Fixes #1239
I just put the single quotes into the right location: The variable. Not the output of the variable, which just prevents it from expanding.
This is an emergency fix since it prevents all game servers that require login from working.

Urgent fix for #1239 (broken Steam login)

---

ARKSurvivalEvolved/arkserver
lgsm/functions/command_details.sh
lgsm/functions/command_stop.sh
lgsm/functions/info_config.sh
lgsm/functions/install_config.sh

ARK
- No more duplicates between .ini and start parms ( fixes #1104 )
- More relevant ports info in command_details.sh
- Added into info_config.sh to get SessionName (servername) from it
- Create config directory before trying to copy config file ( fixes #1235 )
GLOBAL
install_config.sh
- Conditional check for existing cfg file before trying to alter it
- Reworked order and comments
- One liner `for whatever; do` to fit `if` syntax.
Screenshots
http://imgur.com/a/OFPtp

Fix for config issues

---

lgsm/functions/command_debug.sh

Right now when a debug mode is ran and the user aborts the server with Cntrl+C or the server crashes, it leaves a message that kinda seems like LGSM failed:
```
[ OK ] Debug ark-server: Starting debug
Using binned.
4.5.1-0+UE4 7038 3077 402 6
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
^CCtrlCHandler: Signal=2
/home/arkserver1/lgsm/functions/command_debug.sh: line 107: 29308 Aborted ${executable} ${parms}
```
I did some searching around and it doesn't seem like you can remove bash outputting the "Aborted" message, so I thought we could at least end the message off with LGSM confirming that it is stopping it's debug mode.

Adjustment to debug mode

---

Minecraft/mcserver

I have no idea how this was not noticed before.
Without this change the following will happen:
[ FAIL ] Starting mc-server: Executable java -Xmx1024M -jar minecraft_server.jar was not found

Minecraft fix for improper default executable

---

Rust/rustserver
lgsm/functions/check.sh
lgsm/functions/check_executable.sh
lgsm/functions/check_logs.sh
lgsm/functions/check_permissions.sh
lgsm/functions/command_update.sh
lgsm/functions/install_logs.sh
lgsm/functions/logs.sh
lgsm/functions/update_steamcmd.sh

- Rust now allows for custom log locations: log/gamelog
- `details `and `postdetails `commands can now be run even if server is not installed yet #1302
- If executable is not found, the full path will be displayed instead of just the executable name #1288
- Log rotation will now occur upon updates #1075
- Rust will not move gamelog if server is already started #1318
- Checks on /sys will now only occur upon server start #1303
- Fixed a possible error when ${consolelog} doesn't exist
Note: Log rotation already worked with monitor #1075
Also:
- Log directories will now only be created if they don't already exist.
- `gamelog` dir will be created if variable is set but dir doesn't exist
- Legacy server logs (log/server) won't be removed anymore if dir is empty

Loads of minor fixes

---

lgsm/functions/command_console.sh
lgsm/functions/install_logs.sh

`gamelogdir `needs to be created if variable is set, otherwise `check_logs.sh` will attempt to create it upon almost any command if the server wasn't started yet and directory doesn't exist, as per https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/check_logs.sh#L24
symlink is done if `gamelogdir` variable is set rather than checking for what game it is, and after gamelogdir has been created (this order doesn't change anything, just a bit more elegant).
To sum up: Working with `if [ -n $"{gamelogdir}" }]` is a more general and simple way of doing it and shouldn't cause any kind of issue as long as gamelogdir variable is set to the proper path.
Thanks @Khelgar for reporting the issue

Fix logs keep being created with some games with a more general way of handling logs

---

lgsm/functions/core_getopt.sh

Some commands that require setting a variable, like "force-update" wouldn't work without this "eval" argument.
Example:
````
$ ./insserver fu
/home/insserver/lgsm/functions/core_getopt.sh: line 176: forceupdate=1;: command not found
````
This fixes the issue.
Tested on Debian & Ubuntu.

Fixes commands setting vars not working

---

lgsm/functions/command_start.sh

added the ability to set the default width and height of the detatched session using variables tmux_width and tmux_height.
these variables may be set at a local level or system wide.
the script checks if the input from the variables is a valid positive integer and if input is not a valid positive integer, sets the values for the tmux to the default values of 80x23
Fixes #1396

Add tmux dimensions

---

lgsm/functions/command_start.sh
lgsm/functions/info_distro.sh

Fixes #1377 
Trash the integer error as it is not important or script breaking, will just display the version to the user in the `details` command stating it is from the master branch. It is up to the user to determine if the version they compiled is >= 1.6
I also updated the guide on how to compile tmux from source on the wiki.

#1377 - Fixes an issue with compiled copies of tmux

---

lgsm/functions/command_stop.sh

- added support for Terraria
- corrected check order to make proper graceful shutdown work again for MTA and Minecraft
- check for gamenames instead of engines (MTA, Minecraft)

Fixed and extended graceful shutdown

---

Factorio/fctrserver
lgsm/functions/core_dl.sh
lgsm/functions/update_factorio.sh

Added Factorio Experimental build support. Needed to update the core_dl to extract the file properly, as well as added a new variable to switch from "stable" to "experimental". Updated version checking to return 1 line instead of more than 1, which would break the comparison as well.

#1418 factorio experimental

---

lgsm/functions/core_getopt.sh

MTA needs force update to update build revisions that aren't major revisions. We can't detect this ourselves through the logs but this is needed for bug fixes that don't cause a version bump. Note the "BUILD" number on this page:
https://linux.mtasa.com/
Although they did not bump the version, they did bug fixes to the build version. Force updates allows users to get this update.

Allows MTA to force update

---

lgsm/functions/command_backup.sh

Updated the tar exclude to be the configured backup dir, instead of just a hardcoded "backup". This allows for people to change the backup directory location to still be in the game server dir, but in a custom directory. For me specifically it's an NFS mounted directory to backup to my NAS with the cloud backup then enabled on that dir.

Changed tar exclude to be the configured dir

---

lgsm/functions/command_stop.sh

fixed [ .... ] Stopping sdtdserver: Graceful: telnet: 127.0.0.1/home/sdtdserver/lgsm/functions/command_stop.sh: line 91: [: missing `]'

fixed 7days2die stop syntax error [: missing `]'

---

lgsm/config-default/config-lgsm/ut3server/_default.cfg

Duplicate quote in UT3 default config caused server install to fail. Can be merged on code review.

Syntax error in UT3 default config

---

lgsm/functions/update_factorio.sh

This changes the logfile that is used from the log generated by tmux to the log generated by the Factorio binary. As logging is disabled in tmux 1.8, those users which may be stuck on that version cannot use the update functionality, as there is no log to go off of.

Change logfile used for Factorio update check

---

lgsm/functions/alert_pushbullet.sh

As outlined in GameServerManagers/LinuxGSM#1524, the PushBullet alert script was somehow printing the same text twice in a single field. By removing the reply variable from both the fn_rawurlencode() function and from the variables used not 3 lines down, we produce the intended alert.
I made a minor error in a comment where I mislabeled echo as being faster, however the script functions as intended.

Fixed PushBullet alerts duping strings, see #1524.

---

lgsm/functions/command_install.sh

Symlinking the SteamCMD directory into the correct ARK directory so that the mods auto-management will work fine. See http://ark.gamepedia.com/244.3 for the CLI option and Game.ini configuration settings.

Symlinking the SteamCMD dir for ARK

---

lgsm/config-default/config-lgsm/ricochetserver/_default.cfg

Removed duplicated (bad fn_parms, comments) and unsupported (GSLT) stuff.
BTW: Does [Zombie Panic! Source](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/zpsserver/_default.cfg#L19-L22) even support GSLT? I can't find anything about it,

 Corrected Ricochet config

---

lgsm/functions/check_system_requirements.sh

Minor typo fix, ARK server checks for 4GB but warning about 1GB.

Fix ARK dedicated server minimum RAM requirements

---

lgsm/config-default/config-lgsm/csgoserver/_default.cfg
lgsm/config-default/config-lgsm/zpsserver/_default.cfg
lgsm/functions/alert_mailgun.sh
lgsm/functions/fix_csgo.sh
lgsm/functions/info_distro.sh
lgsm/functions/update_factorio.sh
linuxgsm.sh

- added info about custom game mode to the info table (Fixes #1602)
- reordered that table by game type category
- removed GSLT from Zombie Panic! Source because it's not supported
- allow passing of game-, short-, server names as script parameter for installing the specified server
- added message when the given game-, short-, server name is unknown
- changed look of linuxgsm.sh command display
- changed the rest of direct curl calls to ${curlpath}
- improved CS:GO fixes (checks, ..) (Probably fixes #1095)

Minor improvements

---

lgsm/functions/command_backup.sh

This issue has caused enough trouble. Time to annihilate the issue.
Thanks @marvinlehmann for the fix
#1563 
Sample output:
```
arkserver@gaben:~$ ./arkserver b
[  OK  ] Backup arkserver: Backup starting
* Previous backup was created less than 1 day ago, total size 2.7G
[ WARN ] Backup arkserver: arkserver is currently running
* Although unlikely; creating a backup while arkserver is running might corrupt the backup.
[  OK  ] Backup arkserver: Completed: arkserver-2017-10-29-163529.tar.gz, total size 2.7G
arkserver@gaben:~$ du -sh lgsm/backup/*
2.7G    lgsm/backup/arkserver-2017-10-29-155940.tar.gz
2.7G    lgsm/backup/arkserver-2017-10-29-163529.tar.gz
```

Fixes backup backuping itself

---

lgsm/config-default/config-lgsm/rustserver/_default.cfg

Seems like conditionalseed variable (allowing to have seed unset) didn't work as expected with new lgsm updates. So I moved the function to a place where we're sure it's executed: inside fn_parms
Fixes #1691

Ensures conditionalseed mechanics to work 

---

lgsm/functions/command_start.sh

Correct the width and height argument order for the tmux session.

Tmux session size arguments out of order.

---

lgsm/functions/mods_list.sh

Oxide links changed, they now use different repos. I just updated them using git API to find the latest link.

Updated oxide links using git api

---

lgsm/config-default/config-lgsm/sdtdserver/_default.cfg

Fix is easy, removing steam vars makes LinuxGSM use anonymous login :)

sdtd doesn't need steam login anymore

---

lgsm/functions/command_backup.sh

Adding a function to bypass the idiosyncrasies of different realpath implementations which use different syntax.
Also adds an exclusion for backing up the lockfile in the backup tarball.
Ref: #1727, #1752

relative path using readlink instead of realpath

---

lgsm/config-default/config-lgsm/kf2server/_default.cfg

Title says it all. Removes the need to copy the whole fn_parms function into common.cfg/instance config

Make Killing Floor 2 gamemode configurable

---

.github/support.yml

Got a Sentry notification for the bot instance with this error:
```
incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 4, column 19:
supportLabel: Type: support
```

Fix support bot config

---

lgsm/functions/check_status.sh
lgsm/functions/command_start.sh
lgsm/functions/command_stop.sh

This is probably my (not to say "THE") best PR in a while! It resolves an old issue (since LinuxGSM uses TMUX I think) where the wrong tmux session gets killed when they got similar names.
Example: 
```
./csgoserver start
[  OK  ] Starting csgoserver: LinuxGSM
./csgoserver-2 start
[  OK  ] Starting csgoserver-2: LinuxGSM
./csgoserver stop
[  OK  ] Stopping csgoserver: Graceful: sending "quit": 2: OK
./csgoserver-2 stop
[ INFO ] Stopping inferno-2: LinuxGSM is already stopped
```
The reason is:
When graceful shutdown works, probably because of pipe-pane or for whatever reason, the tmux session dies. But `fn_stop_tmux` was ran anyways because it made sense in termes of code. But that caused a command like `tmux kill-session -t csgoserver ` to be ran after the session died, so the command …

Fixes tmux handling of similar session names

---

lgsm/config-default/config-lgsm/svenserver/_default.cfg

Svencoop uses +maxplayers to specify max players, not -maxplayers. If -maxplayers is utilized, it will default to 2 slots regardless of specified players.

Use +maxplayers instead of -maxplayers

---

lgsm/functions/command_update_linuxgsm.sh
lgsm/functions/command_wipe.sh
lgsm/functions/core_getopt.sh

fixes #1830 
- Reorganized the script
- Corrected comments
- Now wipes player.deaths.*.db
- Now wipes sv.files.*.db
- Does not output anything if legacy stuff is not found
- Added `wipeall` (or `wa`) command to wipe blueprints
Tested, works like charm.
For example:
````
ultimatebyte@gaben:~$ ./rustserver wa
Rust data wipe
=================================
Warning! Any user, storage, log and map data from /home/ultimatebyte/serverfiles/server/rustserver will be erased.
Continue? [Y/n] Y
Information! No procedural map file to remove
Information! No procedural map save to remove
Information! No barren map file to remove
Information! No barren map save to remove
Removing server misc srv.files*.db file(s)...OK
Information! No player death to remove
Removing blueprints player.blueprints.*.db …
```

Updated rust Wipe feature & fixed updating when githubbranch differs

---

lgsm/functions/check_ip.sh

resolves #1385 
connects to #1385

Do not exit details if IP is not set

---

lgsm/functions/check_deps.sh

Fixes an issue where non-steam games cannot be installed at all on RedHat based distro because it asks for Debian based dependencies for Steam to be installed, which they cannot.
relates to #1941

Hotfix for RedHat & non steam based game servers

---

lgsm/functions/info_distro.sh

Fixes #1970.
Also uses numfmt which is included in coreutils since version 8.24. _Edit: 8.21_
Ubuntu has this coreutils version since 16.04 _Edit: 14.04_ (https://packages.ubuntu.com/search?keywords=coreutils)
Debian has this coreutils version since 9 (stretch) _Edit: 8 (jessie)_ (https://packages.debian.org/search?keywords=coreutils)
Unfortunately I could neither find out which version of Fedora is necessary nor which other tool one can use to generate human-readable output from the number that we read from /proc/meminfo (which is in kB).

Use /proc/meminfo instead of free -m

---

lgsm/functions/mods_list.sh
linuxgsm.sh

The OxideMod/Oxide.Rust GitHub repository is now found under theumod/umod.rust.
This, of course, has caused Oxide update to fail, and is simply fixed by swapping the URL. The Hurtworld and SevenDaysToDie are still belonging to the OxideMod account, but it may also migrate later.
See: https://github.com/theumod/umod.rust

Fix OxideRust download link

---

lgsm/functions/update_steamcmd.sh

Should fix #1913 
With branch `-beta beta`:
```bash
$ ./stserver update
[  OK  ] Update stserver: Checking for update: SteamCMD: No update available
No update available:
Current version: 3129892
Available version: 3129892
https://steamdb.info/app/600760/
```
Changed to `-beta public`
```bash
$ ./stserver update
[  OK  ] Update stserver: Checking for update: SteamCMD: Update available
Update available:
Current build: 3129892
Available build: 3126493
https://steamdb.info/app/600760/
Applying update...
[  OK  ] Stopping stserver: Graceful: CTRL+c: 3: OK
[  OK  ] Update stserver: SteamCMD
Redirecting stderr to '/home/stserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit -- …
```

use branch name while checking for updates

---

lgsm/functions/command_stop.sh

tmux was sending the -t argument into the session instead of parsing it.

Fix Ctrl C in tmux

---

lgsm/functions/check.sh
lgsm/functions/check_deps.sh
lgsm/functions/check_permissions.sh
lgsm/functions/check_root.sh
lgsm/functions/command_install.sh
lgsm/functions/core_exit.sh
lgsm/functions/info_distro.sh
linuxgsm.sh

dependency checks can now run as root in "server mode" e.g `./csgoserver install` run as root will trigger dependency checking only. Allowing users to install dependencies using LinuxGSM. This will be very useful for automated installations of LinuxGSM

Dependency checking can run as root

---

lgsm/config-default/config-lgsm/csgoserver/_default.cfg

1. game_type
2. game_mode
It's not breaking, sequence doesn't matter, just for readability.
The [official docs](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers) has this way too.

gametype defined first, so it should come first in the params

---

lgsm/functions/mods_list.sh

With the previous "source" Supported Engines value they were listed in every source games (for example in tf2server), which are not supported by these mods. Thx to Lamiiku for finding this and reporting it in Discord.

GOKZ and TTT are only CS:GO mods

---

lgsm/config-default/config-lgsm/csgoserver/_default.cfg

There is no default specific mapgroup for Custom and Wingman.

Add some default mapgroup examples to csgoserver

---

lgsm/functions/check_deps.sh
lgsm/functions/check_permissions.sh

sudo -v prompts when checking for sudo access even with NoPrompt set in sudoers, likewise it will prompt when in auto-install mode. See #2177 for more information as this pull request will ensure no prompt is displayed for Auto-Install, but will prompt if a user has the password set up for sudo in normal mode.
This PR overrules #2180 as it squashes commits
Fixes #2177

Change autoinstall sudo check to resolve #2177

---

lgsm/functions/fix_csgo.sh

The removed code was once required to fix an issue with CSGO workshop files. The removed code is no longer needed and is now an inconvenience rather than a convenience. At CSGO's current state, having LGSM delete workshop files would be a bug.
Thanks for everything. I love the script.
fixes #2188

deprecate: workshop fix that is no longer necessary

---

lgsm/config-default/config-lgsm/ts3server/_default.cfg

It's `ts3server.ini`, not `ts3-server.ini`
It's only in the comment, not in actual code.

fix(ts3server): correct ts3server config file name in comment

---

lgsm/functions/command_fastdl.sh

I have changed the documentation link inside of the fastdl command from the GitHub Wiki to the correct page on https://docs.linuxgsm.com/. 
Fixes #2234

corrected the fastdl command documentation link

---

lgsm/config-default/config-lgsm/bsserver/_default.cfg
lgsm/functions/install_gslt.sh

fix various issues on blade symphony

---

lgsm/functions/command_fastdl.sh

CS:GO with Panorama now supports SVG custom logos, which are displayed in more places than a PNG logo.
Fixes #2297
Edit: unfortunately it's not working for logos out-of-the-box, because the FastDL directory must be the same as in the CS:GO directory structure, so you have to manually create the folders and copy your logo files there.
Bonus:
Extend materials with .png support.

Add SVG support to FastDL

---

lgsm/functions/command_debug.sh

the quake engine have build-in debug function, when enabled by parameter it would generate a file called "Qconsole.log" which contain some useful information 
Fixes #2300

Add debug option for Quake engine

---

lgsm/config-default/config-lgsm/csgoserver/_default.cfg

- no need for `FreeForAll` text for Danger Zone
- add map hint to Danger Zone (only map that can be used with this gamemode at the moment)
- and some indentation fix
```
Co-authored-by: Borzák Attila <1230402+borzaka@users.noreply.github.com>
```

Unnecessary FreeForAll info, add map hint to Danger Zone, indent mod

---

lgsm/config-default/config-lgsm/twserver/_default.cfg

Teeworlds now only allow relative path for config file location, absolute path are not allowed. and config files must placed in same directory as game server binaries. 
This is the only workaround i found after various experiments, existing installation must move config files from /serverfiles directory to /serverfiles/tw (which should affect very few, if any existing installations, as it would be discovered earlier when existing servers updates)
Fixes #2311
```
Co-authored-by: Frisa <digimoncn@gmail.com>
```
When a PR is squashed the author becomes the person who squashed …

Fix Teeworlds config location

---

lgsm/config-default/config-lgsm/nmrihserver/_default.cfg

Enable VAC for NMRIH by default
Fixes #2325
```
Co-authored-by: Frisa <digimoncn@gmail.com>
```

remove the parameter that disable VAC

---

lgsm/config-default/config-lgsm/hwserver/_default.cfg
lgsm/config-default/config-lgsm/qlserver/_default.cfg
lgsm/config-default/config-lgsm/sdtdserver/_default.cfg

* Standardised 32/64 bit binarys are automatically selected for servers without there own script. 
* Removed manual selection for Hurtworld
* Changes to the website now correctly reflect if servers are 32 or 64 bit
Fixes #1436 
```
```
The only workaround for this is to add your details as a co-author. More info about co-authors can be found [here](https://help.github.com/en/articles/creating-a-commit-with-multiple …

feat(config): standardise 32/64 bit binary selection

---

lgsm/config-default/config-lgsm/squadserver/_default.cfg
lgsm/functions/install_config.sh

Fixes #2361
Fixes #2363
```
```

Fix issues for squad

---

lgsm/functions/update_ts3.sh

Fixed two variables in script, so, now update on i686 arch is working fine.
Tested on my own server.
```
Co-authored-by: Kirill Shamilin <kirill@shamilin.ru>
```

fix(ts3server):  fix ability to update TS3 on older i686 arch.

---

lgsm/functions/update_ts3.sh

PR did not fix any issue and was causing tests to fail. Re-tested master version and working OK
Reverts GameServerManagers/LinuxGSM#2367
fixes #2373

Revert "fix(ts3server):  fix ability to update TS3 on older i686 arch."

---

lgsm/functions/command_install.sh

Fix that the empty variable of the gslt is checked instead checking that it is existing
Fixes #2364
```
```

fix(install): check if gslt token empty istead of existing

---

lgsm/functions/command_fastdl.sh

Fix linebreaks for fastdl output
Fixes #2195
```
Co-authored-by: Christian Birk <chirs.h3o66@gmail.com>
```
If documentation does need updating either update it by creating a PR (preferred) or request a documentation …

fix(fastdl): linebreaks for fastdl output

---

lgsm/config-default/config-lgsm/btserver/_default.cfg
lgsm/functions/info_messages.sh

Fix server binary for Barotrauma 
Fixes #2453
```
Co-authored-by: John Doe <chris.h3o66@gmail.com>
```
If documentation does need updating either update it by creating a PR (preferred) or request a documentation …

fix(btserver): Barotrauma has a new server binary location

---

lgsm/functions/command_fastdl.sh

Fixes the fastdl structure
Fixes #2437
```
```
If documentation does need updating either update it by creating a PR (preferred) or request a documentation …

fix(fastdl) #2437 fastdl structure

---

lgsm/config-default/config-lgsm/bt1944server/_default.cfg

Updates to the server start command for Battalion 1994:
1. Change from IP to External IP (#2397) which can solve issues when LinuxGSM is run in a VM - Needs checking please, read my commit comment.
2. Update the reference of `BombGameMode` to `WartideGameMode` to match current server builds.
Fixes #2397
```
Co-authored-by: David Rayner <davidrayner500@gmail.com>
```
The only workaround for this is to add …

Battalion 1944: Updates to start up parameters 

---

lgsm/functions/mods_list.sh
linuxgsm.sh

Fix for oxide/umod download link for linux build.
Fixes #2498

fix(rustserver): new oxide download link for linux build 06.09.2019

---

lgsm/config-default/config-lgsm/untserver/_default.cfg
lgsm/functions/install_server_files.sh
linuxgsm.sh

remove steam auth and remove the 32 bit install fix as it is not needed anymore.
Fixes #2411 

fix(utserver): remove SteamCMD auth requirement 32-bit workaround

---

lgsm/functions/install_config.sh

bug(install): fix a typo breaking bf1942

---

lgsm/functions/check_deps.sh

you cant just change python to python3 in dependency array, because python3 is a META package, not an actually existed package, there's only 2 python package in centos 8: python2 and python36, attempting check python3 results dependency missing
There's no python3 in centos 6 repo so it better leaving it to python2 as the only reason of leaving centos 6 in codebase it keeping it from break (if any still running) existed installations
Fixes #2525

Centos python dep checking V2

---

lgsm/functions/install_header.sh

Before: `Game:Counter-Strike: Global Offensive`
After: `Game: Counter-Strike: Global Offensive`

Add space after "Game:" during install

---

lgsm/functions/alert.sh

fix(alert): fixed typo in config change alert

---

lgsm/functions/check_deps.sh

Removed mono as a dependency as LinuxGSM installs mono 6 using official mono repo. 
eco does not work with mono 6 and only with mono 5
mono 5 is available on official distro repos.
eco will be removing the requirement for mono in release 0.9.0. So there is no point making significant code changes to facilitate this temporary issue.
simply following the dependency requirements on the website will allow eco to work.
Fixes #2549 

fix(eco): remove mono 6 as a dependency for eco (mono 5 still required)

---

lgsm/config-default/config-lgsm/sdtdserver/_default.cfg
lgsm/functions/core_legacy.sh

Fixes sdtd config issue after upgrade to the latest release of lgsm that no config is there in the standard anymore

fix(sdtdserver): restore serverconfig setting

---

lgsm/config-default/config-lgsm/utserver/_default.cfg
lgsm/data/serverlist.csv
lgsm/functions/info_config.sh
lgsm/functions/info_messages.sh
lgsm/functions/info_parms.sh
lgsm/functions/install_server_files.sh

please allow me give a middle finger to epic for abandon this game
Fixes #1666

feat(newserver): Unreal Tournament 4

---

lgsm/config-default/config-lgsm/mcserver/_default.cfg
lgsm/functions/update_minecraft.sh

Currently the update script will only fetch the latest stable release. With this update, you can select `snapshot` as branch instead, which will download the latest snapshot/pre-release/release version.
Not sure about documentation, Minecraft doesn't have any existing docs page that explains the current special config items, so I guess this doesn't need one either?

feat(mcserver): update minecraft server to support release branches

---

.travis.yml
lgsm/functions/check_deps.sh

libstdc++.so.6 can be installed using lib32stdc++6 removing the need to add the i386 arch
Fixes #1896

feat(install): convert libstdc++6:i386 to lib32stdc++6

---

lgsm/functions/check_deps.sh
lgsm/functions/fix_ark.sh

Resolve mods failing after updating to linuxgsm v20.1.0. Problem was caused by the symlink point to /home/arkserver/steamcmd which has been removed if the steamcmd apt package is installed.
The fix will remove the symlink if broken and apply the updated working one.
Fixes #2750 

fix(ark): fix broken steamcmd link preventing mods from working

---

lgsm/functions/info_config.sh

For Teamspeak3-Servers: Only use the first IP specified within the ts3server.ini file. The IP string is cut off after the first appearance of a comma (IP seperator within ts3server.ini files).
As described inte teamspeak server documentation the voice_ip parameter allows a comma separated IP list. Currently when e.g. "voice_ip=12.345.678.910, 1a23:b456:7891:011::1" is specified which is according to ts standards LinuxGSM will extract "12.345.678.910 1a23b45678910111" as IP string and can not deal with it. As a workaround till more then one IP and IPv6 is supported the IP string should be cut off after the first appearance of a comma.
Fixes #2658 
If documentation does need updating either update it by creating a PR (preferred) or request …

fix(ts3server): improve ts3 ip parsing

---

lgsm/functions/alert_telegram.sh

I'm getting this error while trying to use `curlcustomstring="--socks5 192.168.191.1:6080"` as proxy: 
```
[ .... ] Alert tf2server: Sending Telegram alertcurl: option --socks5 192.168.191.1:6080 : is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```
So I make a fix for it. As far as I'm concerned, if `curlcustomstring` contains multiple option it should not use that *quotes*. I tested on my CentOS 7.6 with curl 7.29.0 and it works well.
No need.

fix(alert): resolve bug with telegram curlcustomstring error

---

lgsm/config-default/config-lgsm/acserver/_default.cfg
lgsm/functions/update_steamcmd.sh

appinfo.vdf has been moved to {HOME}/.steam/appcache directory when it was before in {HOME}/Steam/appcache but it hasn't yet been updated in the update script. If we don't delete this file before checking for updates, SteamCMD might not fetch the most up to date BuildID.
I noticed this with the latest csgo update with a freshly installed server when "./csgoserver update" command said that the server is up to date when it wasn't and I needed to use "./csgoserver force-update" command to update it.

remove appinfo.vdf correctly

---

lgsm/functions/check_deps.sh
lgsm/functions/command_backup.sh
lgsm/functions/core_dl.sh
lgsm/functions/install_server_files.sh

Servers that don't use steamcmd have had their archives converted to use .tar.xz as it saw a significant reduction in file size and speed up decompression.
Fixes #2816 

feat(install): convert non-steamcmd game srvers to use tar.xz

---

lgsm/config-default/config-lgsm/pstbsserver/_default.cfg

Fixes Post Scriptum server which does not work properly now.
Game server uses regular spacing not "?" between commands.
Changed reservedslots to 0 as this is a saner default.
Change MaxPlayers to FIXEDMAXPLAYERS.
Added RCON port.
Fixes #2847

Update Post Scriptum _default.cfg

---

lgsm/functions/update_minecraft_bedrock.sh

Summary:
Removed unnecessary ls -tr and shell expansion from the variable as it was not setting the localbuild variable properly. Without this set, the update command would fail out.
```
[mcbserver@linuxgsm ~]$ ./mcbserver update
[ .... ] Update mcbserver: Checking local build: minecraft.net++++++ tail -1
++++++ sed 's/.*Version //'
+++++++ ls -tr /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-05-19:05:59.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-06-03:32:32.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-06-08:30:01.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-06-10:52:34.log /opt/gameservers/mcbserver/log/console/mcbserver-console-2020-05-07-08:31:07.log …
```

fix(update): Minecraft Bedrock issue causing update to not grab the version from logs

---

lgsm/config-default/config-lgsm/avserver/_default.cfg

removed avgalaxy variable in favour of using selfname for galaxy directory. This will also help with multi instance servers
Fixes #2885

feat(avorion): remove avgalaxy variable and replace with selfname

---

lgsm/functions/info_messages.sh

info_messages had a typo for the shortname for StarBound causing the details command to error out when trying to output useful network command.
Fixes #2919

fix(starbound): Details command fix

---

lgsm/functions/query_gamedig.sh

This fix reverts a small change that was made and re-writes it to count the number of objects in the "players" endpoint of the gamedig output.
Fixes #2912 

fix: query_gamedig.sh tuning for correct player count

---

lgsm/functions/check_deps.sh

Removes libtcmalloc-minimal4:i386 (ubuntu) and gperftools-libs (centos) as no longer required and breaks the TF2 on Ubuntu 20.04
Fixes #2849

fix(tf2server): remove libtcmalloc-minimal4:i386 and gperftools-libs

---

lgsm/functions/check_deps.sh

Debian 11 has changed the name of lib32gcc1 to lib32gcc-s1.
I am not updating the website until Debian 11 is released. However, I have added the code ready for the next release of debian.
Fixes #2905

fix(debian 11): change name of lib32gcc1 to lib32gcc-s1 for debian 11

---

lgsm/config-default/config-lgsm/rustserver/_default.cfg

Adds the Rust+ App Port which for Linux appears to be required via command-line.
fixes #2914

feat(rustserver): add support for Rust + app

---

lgsm/functions/info_distro.sh

awk now properly grabs the server pid when spaces are present in the session name
awk now uses the varibale $NF to print the last word on the line instead of the second word on the line
Fixes #2996

fix: awk now properly grabs the server pid when spaces are present in the session name

---

lgsm/functions/core_dl.sh

`./gameserver validate` triggered `steamcmd` to output millions of duplicate lines during download.
Fixes high CPU and huge logfile during `validate`, probably also during download.

fix: resolve steamcmd outputting the same messages to logs

---

lgsm/functions/mods_list.sh

Changes the mod info url to the new domain for exide, what is now known under the name umod
Changed all urls for umod to github as it downloads it anyway from there.
Also improve the parsing of the huntworld download url with jq

fix(mods): change url to new domain for oxide + redo last version fetch

---

lgsm/functions/info_config.sh

With the current config parting for the sdtd port it can happen, that all numbers in the same line can be parsed as the port.
Fixes #3006

fix(sdtdserver): config parsing for the port

---

lgsm/functions/update_minecraft_bedrock.sh

Fix update /install of Minecraft Bedrock server, as the site what we scrape, does do a redirect somewhere else.
Fixes #2980

fix(mcb): update fails, as the site does a redirect and does not follow

---

lgsm/functions/update_factorio.sh
lgsm/functions/update_minecraft.sh
lgsm/functions/update_minecraft_bedrock.sh
lgsm/functions/update_mta.sh
lgsm/functions/update_mumble.sh
lgsm/functions/update_steamcmd.sh
lgsm/functions/update_ts3.sh

Resolve Minecraft updater no longer working after recent update to Minecraft
Mojang altered the console output to use `\r` Windows file ending. Breaking the version comparison
Fixes #3066

fix(update): resolve broken minecraft updater since v1.16.3

---

lgsm/functions/check_deps.sh

Add missing dependency `libncurses5:i386` for bf1942 server 
Fixes #3097 

fix(bf1942): add missing dependency to checks for libncurses5:i386

---

lgsm/functions/info_config.sh

Fixes the servername parsing with a more strict parsing
Fixes #3095 

fix(bf1942): servername parsing

---

lgsm/functions/check_deps.sh

changes the dependency for ubuntu 20.10 to lib32gcc-s1
Fixes #3093 

fix(deps): change ubuntu 20.10 to use lib32gcc-s1

---

lgsm/config-default/config-lgsm/pvrserver/_default.cfg
lgsm/data/serverlist.csv
lgsm/functions/check_system_requirements.sh
lgsm/functions/fix_steamcmd.sh
lgsm/functions/info_config.sh
lgsm/functions/info_messages.sh
lgsm/functions/info_parms.sh
lgsm/functions/install_config.sh

feat(new server): pvrserver

---

lgsm/functions/update_minecraft.sh

When the branch for minecraft is set, This should allow lgsm to download a previous version. 
I haven't actually tested this in LGSM yet, I only tested the updated jq command manually:
```
curl -s "https://launchermeta.mojang.com/mc/game/version_manifest.json" | jq -r '.versions | .[] | select(.id=="1.15") | .url'
```
Previously it would always grab the latest MC version, even if the branch was set. 
The branch [defaults](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/mcserver/_default.cfg#L20) to "release", so as long as no one has changed that this shouldn't impact anyone's current configs 
Fixes #[issue]
If documentation does need updating either update it by creating a PR (preferred) or …

fix(mcserver): Support installing previous minecraft versions via branch

---

lgsm/functions/update_steamcmd.sh

This change fixes the update command for those on public branches. Possibly needs testing and confirmation.
Fixes #3072 
Fixes #3079
Fixes #3106
Fixes #3129
Fixes #3131 
Check if branch var is 'public' to use correct `remoteBuild` execution.
* [?] This pull request uses the `develop` branch as its base.

During update, check against branch being public.

---

lgsm/functions/command_stop.sh

When executing the stop command whilst something is still typed in the server session (enter was not pressed), the stop command will time out and fail, requiring manual intervention.
Fixes #3141 
This fix is rather crude, I have tried to clear the command that was typed in without executing it (which could cause unwanted behavior). But I was ultimately unsuccessful and this fixes the actual issue just fine (also lots of server operations are lost on stop anyways).
Also pardon my old (now "drafted") PR I made. I'm still figuring out how GitHub works.

fix(stop) stop will clear tmux text before entering stop command

---

lgsm/functions/check_deps.sh

Adds the dependency for debian and ubuntu for 32bit to fix the "error"
Message:
`Failed to init SDL priority manager: SDL not found`
Fixes #2701

fix(steamcmd): add dependency SDL 32bit for debian and ubuntu

---

lgsm/config-default/config-lgsm/csgoserver/_default.cfg
lgsm/functions/command_stop.sh

Changes stop mode to 9 (GoldSrc) to take in to account `-autoupdate` in the arguments.
Fixes #2992

fix(stop): change csgoserver stop mode

---

lgsm/config-default/config-lgsm/vhserver/_default.cfg

Adds a variable `savedir` with it set to the default location that valheim dedicated server currently uses. This is to avoid any breaking changes.
Fixes #3253

fix:(vhserver) Add support for changing savedir in valheim

---

lgsm/config-default/config-lgsm/vhserver/_default.cfg

The current single tick quotes do not work as intended when using spaces in the server name. 
I instead used escaped quotes (tested + working) and added it to the password and world name for sanities sake.

fix(vhserver): Add escaped quotes to Valheim startparams to account for spaces

---

lgsm/functions/check_system_requirements.sh
lgsm/functions/command_send.sh
lgsm/functions/core_functions.sh
lgsm/functions/core_getopt.sh
lgsm/functions/core_messages.sh
linuxgsm.sh

Added a function to send command directly to the console
Fixes #1917

feat(send): new command send

---

lgsm/functions/info_distro.sh

The most recent backup was previously being chosen as the first file in the backup folder when it's actually the last.  This change fixes that issue.
Fixes #3307 

fix(info): get most recent backup instead of oldest

---

lgsm/functions/command_start.sh

Quoting the command and arguments causes tmux to treat it as a single command with spaces in it. Remove the quotes so tmux properly runs the command and passes arguments.
Fixes #3239

Update command_start.sh to not quote command

---

lgsm/functions/info_distro.sh

Find does not sort results, it displays them in the order they are found.  In this case, this may usually be the order the backups are found, it is possible that it is not.  Also, `ls -1tr` is lighter than `find -print0 | sort -xargs 0`, and we're not using any of the advanced features of find.  So why not use a lighter command and force a sorted result where -head and -tail work well.
Use `ls -1tr` in place of `find`
* produce a simple list,
* one item per line,
* sorted by date reverse. (this is the part find does not do easily)
Fixes #[3319]
* Dev docs: …

Force $lastbackup to use latest backup.

---

lgsm/functions/command_start.sh
linuxgsm.sh

startparameters set instead of parms and call function to eval parms once
fixes regression from #3315

fix: startparameters set instead of parms and call reload parms

---

lgsm/config-default/config-lgsm/rustserver/_default.cfg

Add per default the gamemdoe option to the parameters and the default "vanilla" value to the config
New gamemodes will be also on this page: https://wiki.facepunch.com/rust/server-gamemodes
Fixes #3334 

feature(rust): add option to set gamemode for server

---

lgsm/functions/command_fastdl.sh

Adds vmt and vtf to file extentions for fastdl
Fixes #3294 

fix(fastdl): add missing file extention vmt and vtf

---

lgsm/functions/check_deps.sh

Adds a check to detect a lxc container and add hostname as dependency
Fixes #3248 

fix(deps): add detection for lxc container add hostname dependency

---

lgsm/functions/info_parms.sh

Disabled gameserver query if public is set to 0. When the server is in private mode the query port becomes disabled
Fixes #3337 

fix(valheim): disable queryport if public is set to 0

---

linuxgsm.sh

This fix will allow the legacy `parms=` to work if still present in the LinuxGSM configs.
Fixes #[issue]

fix(config): parms setting will work again if present in configs

---

lgsm/functions/check_deps.sh
lgsm/functions/info_distro.sh
lgsm/functions/info_messages.sh

Add Java 16 as a dependency requirement for Ubuntu 20.04 and above
Fixes #3479

fix(mc): add Java 16 as a dependency requirement for Ubuntu 20.04 and above

---

lgsm/functions/check_steamcmd.sh
lgsm/functions/core_steamcmd.sh

Fixed Disk Write failure bug created with recent update to SteamCMD
```
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
ERROR! Failed to install app '232330' (Disk write failure)
```
Fixes #3481

fix(steamcmd): resolve Disk write failure bug

---

lgsm/functions/core_functions.sh
lgsm/functions/info_game.sh
lgsm/functions/info_messages.sh
lgsm/functions/info_stats.sh

This PR will add stats collection on alert types being used in LinuxGSM. This info will be added to the [LinuxGSM stats dashboard](https://linuxgsm.com/data/usage/) and will allow us to see which types of Alerts users prefer. This will help guide development priorities and future alert additions.
Fixes #3551

feat(stats): allow stats on which alerts are being used

---

lgsm/functions/install_server_files.sh

Fixes #3683 after [the 2.78.1 archive](https://mega.nz/file/V5wSkZxB#1buLEmF7uLnE-O08MURG4UqGLEfDrpWHpkO4hgo9tsM) is uploaded to http://linuxgsm.download/WolfensteinEnemyTerritory/etlegacy-v2.78.1-i386-et-260b.tar.xz
Sidenote: I noticed in the archive currently used contains files that I think are not required. This is the original 2.78.1 file with the required pk3 files added to etmain and some icon, metainfo, etc files removed that aren't required for a server. Similar to the 2.77.1 files created previously.
* Dev docs: …

feat(etl): update Enemy Territory: Legacy to 2.78.1

---

lgsm/functions/mods_core.sh

Major refactor of fn_mod_lowercase()
Finally fixes mods lowercase conversion
Fixes #1868
```
Installing DarkRP
=================================
creating mod download directory /home/ulti/lgsm/mods/tmp...OK
#=#=-  #       #                                                                                                                                                                                                       ################################################################################################################################################################################################################################################ 100.0%   -#O=-   #         #           # …
```

fix: #1868 mods lowercase conversion

---

lgsm/config-default/config-lgsm/pzserver/_default.cfg

`-ip` is not parsed correctly by the new build 41 release. See https://github.com/GameServerManagers/LinuxGSM/discussions/3711#discussioncomment-1844368
Fixes #3711 

fix(pzserver): start with --ip instead of -ip

---

lgsm/functions/check_config.sh

Give a message to the user, when the password is not long enough
Fixes #3737

fix(vh): log a message when the password is not set or to short

---

linuxgsm.sh

Add a way to set github user, repo and branch at runtime  with 3 env var instead of creating/editing variables githubuser, githubrepo and githubbranch in source file.
* LGSM_GITHUBUSER
* LGSM_GITHUBREPO
* LGSM_GITHUBBRANCH
Usefull in any automate use case.
This help a lot when automate deployment processus
It helps automation from the very begining when just calling at first step linuxgsm.sh and also for the other steps (./gameserver.sh install) without editing nor creating files.
One use case is when playing with docker where we use a lot of env var to automatize workflow.
This feature is an option, it does not break the previous way of using lgsm
If documentation does need updating either update it by creating a PR (preferred) or …

feat(github): Allow to set  github user, repo and branch at runtime with environment variable

---

lgsm/config-default/config-lgsm/sdtdserver/_default.cfg

7 Days to Die no longer supports the UDP `protocol-valve` for gamedig and gsquery. This causes the monitor to always fail and restart the server.
To fix this, switch to the `tcp` query mode. This matches the info shown in the `details` output:
```
DESCRIPTION  PORT   PROTOCOL  LISTEN
Game         26900  udp       1
Game+2       26902  udp       2
Query        26900  tcp       1
Web Admin    8080   tcp       0
Telnet       8081   tcp       1
```
Fixes #3619
Related to #3701
N/A

fix(sdtdserver): monitor command fails

---

lgsm/config-default/config-lgsm/arma3server/_default.cfg

Fixes loading multiple mods failing due to accidental line termination in the mod string when following the documentation. (Observed on Ubuntu 20.10)
If you want this linked to an issue then reject the pull request.

fix (arma3server): prevent multiple loading mods failing due to accidental line termination

---

lgsm/functions/info_distro.sh
lgsm/functions/info_game.sh

move steammaster check and extip code to info_game.
This is needed that the queryport for some games is only in the info_game.sh
Fixes #3762

refactor: move steammaster check to info_game

---

.github/workflows/create-release.yml
.github/workflows/labeler.yml
.github/workflows/lock.yml
.github/workflows/version-check.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

lgsm/functions/fix_csgo.sh

With the incompatibility of the `libgcc_s.so.1` with Ubuntu 22.04 we just move away the lib to use the system lib instead.
Fixes #3958

fix(csgo): move away old libgcc_s.so.1 to fix sourcemod

---

lgsm/config-default/config-lgsm/stserver/_default.cfg

There are some unforseen issues if you both specify load and new together.
Loadlatest will also grab the last backup of that same save.
Fixes:
* Bug Fix: Specifying new and load together spawned a lander (starting new world supplies) every time the server was restarted.

feat(st): switch parameters to loadlatest

---

lgsm/data/ubuntu-20.04.csv
lgsm/data/ubuntu-21.04.csv
lgsm/data/ubuntu-21.10.csv
lgsm/data/ubuntu-22.04.csv

Fixes the dependencys for rw and pz on Ubuntu
On Ubuntu only on a few the package openjdk-16-jre does still exist, so i replaced here all occourences for this.
Also rng-tools has a new package with the name rng-tools5 in ubuntu 22.04 - changes this as well.
Edit: java 17 is LST, this is why this makes sense to update to this version.
Fixes #3910

fix(deps): fix java and rng dependency for pz and rw

---

lgsm/functions/query_gsquery.py

I replaced optparse with argparse and refactored some process to check arguments.
Breaking change: Status code 4 no longer occurs because argparse checks whether an argument is passed.
Fixes #3912 
* https://github.com/GameServerManagers/LinuxGSM-Dev-Docs/pull/2
* https://github.com/GameServerManagers/LinuxGSM-Docs/pull/84

fix: replace deprecated optparse with argparse

---

lgsm/config-default/config-lgsm/emserver/_default.cfg

Changed defaultmap value from "emp_district" to "con_district402" as this map was renamed years ago and would otherwise cause the server to fail on startup.
Fixes #[3976]

fix(em): update default map

---

lgsm/functions/command_check_update.sh
lgsm/functions/core_getopt.sh
lgsm/functions/update_ts3.sh

Add check-update frunction for Teamspeak 3
Fixes #3522

feat(ts3): add check-update function

---

lgsm/functions/info_game.sh

queryport was being overwritten with rconpassword or "NOT SET"
Fixes #3981

fix(wmcserver): Fix not being able to read query port

---

lgsm/config-default/config-lgsm/vpmcserver/_default.cfg
lgsm/data/almalinux-8.csv
lgsm/data/centos-8.csv
lgsm/data/debian-10.csv
lgsm/data/debian-11.csv
lgsm/data/rhel-7.csv
lgsm/data/rhel-8.csv
lgsm/data/rocky-8.csv
lgsm/data/serverlist.csv
lgsm/data/ubuntu-18.04.csv
lgsm/data/ubuntu-20.04.csv
lgsm/data/ubuntu-21.04.csv
lgsm/data/ubuntu-21.10.csv
lgsm/data/ubuntu-22.04.csv
lgsm/functions/command_stop.sh
lgsm/functions/command_update.sh
lgsm/functions/info_game.sh
lgsm/functions/info_messages.sh
lgsm/functions/install_server_files.sh
lgsm/functions/update_papermc.sh

feat(newserver): add Velocity Proxy

---

lgsm/config-default/config-lgsm/csgoserver/_default.cfg

This PR adds the `sv_skirmish_id` and `sv_game_mode_flags` cvars required by newer game modes to csgoserver's LGSM config, which enables users to select all available game modes.
Closes #4004 
-   [X] New feature (change which adds functionality).
-   [X] Comment update (typo, spelling, explanation, examples, etc).
-   [X] This pull request uses the `develop` branch as its base.
-   [X] This pull request Subject follows the Conventional Commits standard.
-   [X] I have performed a self-review of my …

feat(csgoserver): add all game mode related cvars to CS:GO LGSM config

---

lgsm/data/almalinux-8.csv
lgsm/data/centos-7.csv
lgsm/data/centos-8.csv
lgsm/data/debian-10.csv
lgsm/data/debian-11.csv
lgsm/data/debian-9.csv
lgsm/data/rocky-8.csv
lgsm/data/ubuntu-16.04.csv
lgsm/data/ubuntu-18.04.csv
lgsm/data/ubuntu-20.04.csv
lgsm/data/ubuntu-21.04.csv
lgsm/data/ubuntu-22.04.csv
lgsm/functions/fix_bt.sh

Fixes #4003
-   [ ] New feature (change which adds functionality).
-   [x] This pull request Subject follows the Conventional Commits standard.
-   [x] I have provided a detailed with …

fix(bt): add convertion of the startscript to LF

---

lgsm/config-default/config-lgsm/ut99server/_default.cfg
lgsm/functions/alert.sh
lgsm/functions/command_backup.sh
lgsm/functions/command_check_update.sh
lgsm/functions/command_install_resources_mta.sh
lgsm/functions/command_mods_update.sh
lgsm/functions/command_update.sh
lgsm/functions/core_dl.sh
lgsm/functions/core_exit.sh
lgsm/functions/core_functions.sh
lgsm/functions/core_getopt.sh
lgsm/functions/core_steamcmd.sh
lgsm/functions/fix.sh
lgsm/functions/info_game.sh
lgsm/functions/install_eula.sh
lgsm/functions/install_server_files.sh
lgsm/functions/install_ts3db.sh
lgsm/functions/mods_core.sh
lgsm/functions/update_factorio.sh
lgsm/functions/update_jediknight2.sh
lgsm/functions/update_minecraft.sh
lgsm/functions/update_minecraft_bedrock.sh
lgsm/functions/update_mta.sh
lgsm/functions/update_papermc.sh
lgsm/functions/update_ts3.sh
lgsm/functions/update_ut99.sh
lgsm/functions/update_vintagestory.sh

A refactor to UT99 updating that turned into a refactor of non-steam updaters
#4147
Key changes
* [feat(ut99): add oldunreal update functionality](https://github.com/GameServerManagers/LinuxGSM/pull/4146/commits/0b18b31326afc1382089463c7d2b02160779faad)
* [non-steam update refactor](https://github.com/GameServerManagers/LinuxGSM/pull/4146/commits/fe4e9a535f38e65a1a48e58fca5f9c4f5645da19)
* [feat(ut99): now supports native x64](https://github.com/GameServerManagers/LinuxGSM/pull/4146/commits/b4175e5890b0ad032b96f52a9413cef8ad745f24)
* Check update now available for all servers
* [improve progress bar](https://github.com/GameServerManagers/LinuxGSM/pull/4146/commits/888535e99eed584b2ff533e5780cbd99ec832a1d)
-   [ ] New feature (a change which …

feat: update refactor

---

lgsm/functions/command_update_linuxgsm.sh

If lgsm updates itself it cds into functions directory but not back, this is in at least one case an issue.
Fixes #[issue] Discord LGSM cannot update itself, breaks when checking lgsm module
Got the same error some time ago as well: https://github.com/jusito/docker-ttt/issues/9
In the "files changed" it looks weird, basically I just wrapped the cd into ( cd ".."; do somethin), this ensures that even if it exits somewhere in between it will cd back if outside of the block.
Check the log before and after "a server is already installed" for the first log is shows function directory.
```bash
#!/bin/bash
set -euo pipefail
function stop_after_update() {
pid="$1"
while ! grep -F 'Checking Dependencies' gmodserver.log; do
sleep 1s
done
kill "$pid"
while ps -p "$pid" -o pid= > /dev/null 2>&1; do …
```

fix(update-lgsm): incorrect wdir sometimes

---

lgsm/functions/query_gamedig.sh

should always provide "querystatus" and in particular on fail != 0 for monitor command & a typo in a variable name

fix(gamedig): default exitcode & var name

---

lgsm/functions/info_messages.sh

if referenced queryport / voiceport is "NOT SET" grep would look for NOT in the file SET and silently fail

fix(details): port output with whitespaces fails silently

---

lgsm/functions/install_server_files.sh

fix: install successful without installation files

---

lgsm/config-default/config-lgsm/pzserver/_default.cfg

Add option to configure project zomboïd server memory usage.
Avoid modifying server configuration files and allow using different settings per instances
I'm not found of configuring gigabytes with megabytes values and would like to refactore javaram to also take the unit (as in `javaram="8G"`) and just do `-Xmx${javaram}` if that is ok with you I'll update the PR to also include that.
I've rapidly checked and javaram is only use to display java version in details if set. Nothing seems bound to a megabyte only usage (except perhaps old java versions ?)
Fixes #3056
-   [ ] Comment update (typo, …

feat(pzserver): Add option to configure server memory usage

---

.github/workflows/details-check.yml
.github/workflows/serverlist-validate.sh
.github/workflows/serverlist-validate.yml
.github/workflows/version-check.yml
lgsm/data/almalinux-8.csv
lgsm/data/almalinux-9.csv
lgsm/data/centos-7.csv
lgsm/data/centos-8.csv
lgsm/data/centos-9.csv
lgsm/data/debian-10.csv
lgsm/data/debian-11.csv
lgsm/data/debian-12.csv
lgsm/data/debian-9.csv
lgsm/data/rhel-7.csv
lgsm/data/rhel-8.csv
lgsm/data/rhel-9.csv
lgsm/data/rocky-8.csv
lgsm/data/rocky-9.csv
lgsm/data/serverlist.csv
lgsm/data/ubuntu-16.04.csv
lgsm/data/ubuntu-18.04.csv
lgsm/data/ubuntu-20.04.csv
lgsm/data/ubuntu-21.04.csv
lgsm/data/ubuntu-21.10.csv
lgsm/data/ubuntu-22.04.csv

Add github action to check all dependency csv file match up
Fixes #[issue]
-   [x] I have provided a detailed enough …

feat: serverlist validate

---

lgsm/data/almalinux-9.csv
lgsm/data/centos-9.csv
lgsm/data/rhel-9.csv
lgsm/data/rocky-9.csv

- python36 is no longer available in the repo list for rhel-9 & centos-9
- not possible to use "dnf install python36" or "yum install python36", manually compiling from source or using pyenv is only way to install python36 (from testing)
- switching from python36 to python3 in lgsm data files works for latest rhel-9 (redhat9) dev build
- tested with csgoserver, running without issues after running commands:
```
./linuxgsm.sh install
<selected csgoserver from gui>
./csgoserver install
./csgoserver start
./csgoserver console
```
Fixes [#4202] 
-   [ ] Comment update (typo, spelling, explanation, …

python version change for rhel-9 & centos-9

---

linuxgsm.sh
tests/tests_fctrserver.sh
tests/tests_jc2server.sh
tests/tests_mcserver.sh
tests/tests_ts3server.sh

feat: improve error message for unknown game server
Fixes #4217
-   [ ] I have provided a detailed enough description …

feat: improve error message for unknown game server

---

lgsm/modules/check_system_dir.sh
lgsm/modules/install_config.sh

Migrates configs from master to main branch. using shortname instead of gamedirname
Fixes #[issue]
-   [x] I have …

feat: game server config migration

---

lgsm/functions/info_game.sh
lgsm/modules/info_game.sh

Config variables `a2sQueryEnabled` and `steamQueryPort` was removed in 0.9.9.31.
This fixed config parser for new a2s entities.
This is continuation of https://github.com/GameServerManagers/LinuxGSM/pull/4240
Both https://github.com/GameServerManagers/LinuxGSM/pull/4240, and this one, use https://github.com/GameServerManagers/Game-Server-Configs/pull/135 changes in Config repo and should be released in parallel.
Fixes #4239
-   [x] This …

fix(armar): fix parsing new a2s config

---

lgsm/modules/info_distro.sh
lgsm/modules/info_game.sh
lgsm/modules/info_stats.sh

LinuxGSM stats has been migrated to use Google GA-4 which replaces Google Universal Analytics (UA). This PR drastically streamlines and reduces the number of curl requests to analytics. The only missing functionality currently is country which is not yet available in the event-driven API (hopefully will be added later).
New stats added for virtual environment type which will help identify people useing the docker container, bare metal, or VM.
Fixes #[issue]
-   [ ] This pull …

feat: Migrate stats to Google GA-4

---

lgsm/modules/info_game.sh

The sed command in the fn_info_game_valve_keyvalues function has been modified to improve its functionality. The change ensures that only the value between double quotes is captured, even if there are additional spaces before or after the value. This enhances the accuracy of extracting values from server configuration files.
Fixes #4222 
-   [x] This pull request uses the …

fix: improve sed command in fn_info_game_valve_keyvalues

---

lgsm/modules/check_deps.sh

For reasons unknown you can install dpkg in RHEL so instead this now looks for apt, yum or dnf
Fixes #4251 
-   [x] I …

fix: resolve edge case where RHEL servers might have dpkg installed

---

lgsm/modules/info_game.sh
lgsm/modules/info_messages.sh

updated the public ip provider to http://ip-api.com.json that can provide more detail about a servers public ip. This will allow alerts to in future provide more details
Fixes #[issue] …

feat: convert public ip to json

---

lgsm/functions/query_gamedig.sh
lgsm/modules/query_gamedig.sh

Replaces the link references to the node-GameDig repository to the actual one.
Fixes #4337.
-   [x] Comment update (typo, spelling, explanation, examples, etc).
-   [x] I have provided a …

docs: replace gamedig repository links to the actual repository

---

lgsm/modules/core_messages.sh

When using "ansi"="off", the escape sequence \033[K is still present and tools that input from lgsm will get thoses bytes.
This commit removes that.
One side-effect if two prints are done without a line feed and the second is shorter than the first, then some unwanted character could remain.
```
echo -en "${creeol}foo/bar"
echo -en "${creeol}foo"
```
* before : prints "foo"
* after: prints "foo/bar"
-   [x] This pull request links to an issue. (The bug is in the PR)
-   [x] This …

refactor: remove ansi sequence from creeol when ansi=off

---

lgsm/config-default/config-lgsm/vhserver/_default.cfg

Valheim world modifiers can be set in the executable start parameters as is documented in the manual pdf included in the server root directory.
Initially I wanted to create a separate config string for each modifier type but since they can be used multiple times (they can be mixed with each other) we would need complex logic to handle it that cannot fit in the cfg file.
for example: let's say I want to have a world with no raids, hard portals and easy no map, i would need to add these parameters:
`-modifier raids none -modifier portals veryhard -setkey nomap`
notice how `-modifier` is used twice and uses a combination of key and value, ideally we should have a `modifier` csv string with all the options that can be split into an array and then iterate on it to form the final string. But …

feat(vh): add an additional config string for valheim world modifiers

---

lgsm/config-default/config-lgsm/gmodserver/_default.cfg

Removes authkey as it is not required anymore on gmodserver
Fixes #4369
-   [x] I have provided a detailed enough …

fix(gmod): Remove authkey

---

.github/workflows/labeler.yml
lgsm/config-default/config-lgsm/arma3server/_default.cfg

This removes the quotes around the mod list as it appears in the command line parameters.  This was breaking mod loading.
This reverts a change made by PR #3845, so I expect this may need discussion.
Fixes #4021
-   Bug fix (a change which fixes an issue).

fix(arma3server): remove quotes from around mod list in Arma3 server command line

---

lgsm/config-default/config-lgsm/rustserver/_default.cfg
lgsm/modules/fix_rust.sh

Forces `screen-256color` if using Oxide and tmux 3.3 and above.
Fixes #4267
-   [x] I have provided a detailed enough …

 fix(rust): add default-terminal setting for Oxide

---

lgsm/modules/check_deps.sh

Debian has added non-free-firmware repo. This was being detected alongside non-free and causing issues with steamcmd installation. this fix ensures non-free is only detected.
Fixes #4374 
-   [x] I have performed a self-review of my …

fix(install): non-free is now correctly detected

---

lgsm/config-default/config-lgsm/kfserver/_default.cfg
lgsm/modules/fix.sh
lgsm/modules/fix_armar.sh
lgsm/modules/fix_kf.sh

Allows KF Server to show up in the steam server browser
Fixes #4389 
-   [ ] I have provided a detailed enough …

fix(kf): ensure newer steamclient.so is copied to serverfiles

---

lgsm/config-default/config-lgsm/ns2server/_default.cfg
lgsm/modules/info_game.sh
lgsm/modules/info_messages.sh

update start parameters to add mod server. This updates start parameters based on NS2 updates
Fixes #3875
-   [x] I …

feat(ns2): update start parameters to add mod server

---

lgsm/modules/query_gsquery.py

Hi,
since a few months I have a problem that the first query for ./wfserver monitor works fine but subsequent are not. Therefore the server will be restarted every time one does run the monitor command.
It seems that the python gameserver query had a misspelling for the "protocol-quake3" which lead to false offline notifications for both quake2 and quake3 servers because quake2 wasn't found anymore and quake3 used the quake2 command to check for the server response.
Fixes #4409
- …

fix(monitor): Quake2/Quake3 query fix for ./wfserver monitor (and other quake games)

---

lgsm/modules/mods_list.sh

Fixes the update URL of the Valheim plus mod. Currently installing the mod will pull the updated Grantapher/ValheimPlus fork, but updating will pull the outdated valheimPlus/ValheimPlus.
fixes #4437 
-   [x] I have performed a …

Fix valheimplus updateurl

---

.github/workflows/add-to-project.yml
.github/workflows/details-check.yml
.github/workflows/git-sync.yml
.github/workflows/labeler.yml
.github/workflows/lock.yml
.github/workflows/potential-duplicates.yml
.github/workflows/serverlist-validate.yml
.github/workflows/trigger-docker-build.yml
.github/workflows/update-check.yml
.github/workflows/update-copyright-years-in-license-file.yml
.github/workflows/version-check.yml

[i opted to remove the PR template for this particular pull due to its non-user-facing nature, thanks!]
the most prominent case being update-copyright-years-in-license-file altering commit history in forks depending on configuration (sometimes these type of PRs just auto-merge on forks, creating a merge conflict when they sync their fork for preparing a PR) additionally, some actions require secrets so they would fail anyway

chore: only run GitHub actions when on main account

---

lgsm/config-default/config-lgsm/rustserver/_default.cfg

Adds a new parameter to the rustserver config, that allow specification of server browser tags. Those tags will be displayed on your server in the server browser.
Fixes #4417
-   [x] I …

Add server browser tags to rustserver config

---

lgsm/config-default/config-lgsm/pwserver/_default.cfg
lgsm/modules/info_game.sh

Allows the user to set steamqueryport & gameserver port in the start parameters
Fixes
https://github.com/GameServerManagers/LinuxGSM/issues/4454
-   [X] New feature (a change which adds functionality).
-   [X] This pull request uses the `develop` branch as its base.
-   [X] I have performed a self-review of my code.
-   [X] I have checked that this code …

feat(pwserver): port & steamport setting for palworld

---

lgsm/modules/mods_list.sh

Fixes #4547
-   [X] This pull request uses the `develop` branch as its base.
-   [X] This pull request subject follows the Conventional Commits standard.
-   [X] I have performed a self-review of my code.
-   [X] I have checked that this code is commented where required.
-   [X] I have provided a detailed …

fix(vh): update bepinexvh url to new url #4547

---

lgsm/data/almalinux-8.csv
lgsm/data/almalinux-9.csv
lgsm/data/centos-7.csv
lgsm/data/centos-8.csv
lgsm/data/centos-9.csv
lgsm/data/rhel-8.csv
lgsm/data/rhel-9.csv
lgsm/data/rocky-8.csv
lgsm/data/rocky-9.csv
lgsm/data/ubuntu-20.04.csv
lgsm/data/ubuntu-22.04.csv
lgsm/data/ubuntu-23.04.csv
lgsm/data/ubuntu-23.10.csv
lgsm/modules/info_game.sh

As of the [latest patch](https://feedback.minecraft.net/hc/en-us/articles/26136167989005-Minecraft-Java-Edition-1-20-5-Armored-Paws), minecraft now requires Java 21 to run:
> The game now requires Java 21
Other distro's csv files also have to be updated.
Fixes #4564 
-   [x] This code follows the …

fix(mcserver): change required jdk to 21

---

lgsm/modules/update_mc.sh

If the executable variable is modified, fn_update_dl does not update minecraft_server.jar and which is used in fn_update_localbuild.
In addition this creates a problem if a alternative executable is used to launch minecraft by overwriting it.
Fixes N/A
-   [x] This code follows the style guidelines …

fix(mcserver): alternative executable results in update loop and overwriting the executable.

---

lgsm/config-default/config-lgsm/vhserver/_default.cfg
lgsm/data/almalinux-8.csv
lgsm/data/almalinux-9.csv
lgsm/data/centos-7.csv
lgsm/data/centos-8.csv
lgsm/data/centos-9.csv
lgsm/data/debian-10.csv
lgsm/data/debian-11.csv
lgsm/data/debian-12.csv
lgsm/data/debian-9.csv
lgsm/data/rhel-7.csv
lgsm/data/rhel-8.csv
lgsm/data/rhel-9.csv
lgsm/data/rocky-8.csv
lgsm/data/rocky-9.csv
lgsm/data/ubuntu-16.04.csv
lgsm/data/ubuntu-18.04.csv
lgsm/data/ubuntu-20.04.csv
lgsm/data/ubuntu-22.04.csv
lgsm/data/ubuntu-23.04.csv
lgsm/data/ubuntu-23.10.csv
lgsm/data/ubuntu-24.04.csv

Based on the following reddit thread https://www.reddit.com/r/valheim/comments/xshlyk/dedicated_server_on_linux_crossplay_switch_not/
Enabling crossplay on linux server required installing some additional dependencies. Out of the 3 mentioned there only `libatomic1` and `libpulse-dev` seem to be required.
Once they have been installed and `-crossplay` flag is set the server succesfully registers with PlayFab and is visible in microsoft store version of the game.
I've only tested this setup on Ubuntu 22.04 and was able to see the server both in steam browser and in xbox pc version.
Server logs show the following PlayFab registration and join code assignment:
```
03/23/2024 21:35:49: Game server connected
03/23/2024 21:35:52: Joined PlayFab Party network with ID "<REDACTED>"
03/23/2024 …
```

feat(vhserver): enable crossplay support

---

lgsm/modules/alert_discord.sh
lgsm/modules/alert_gotify.sh
lgsm/modules/alert_ifttt.sh
lgsm/modules/alert_pushbullet.sh
lgsm/modules/alert_pushover.sh
lgsm/modules/alert_rocketchat.sh
lgsm/modules/alert_slack.sh
lgsm/modules/alert_telegram.sh
lgsm/modules/command_update_linuxgsm.sh
lgsm/modules/core_dl.sh
lgsm/modules/core_github.sh
lgsm/modules/info_game.sh
lgsm/modules/mods_list.sh
linuxgsm.sh

changed default timeout of curl from 10 seconds to 3 seconds to prevent slowness.
Fixes #4462
-   [ ] I have provided …

feat: change curl default timeout to 3 seconds

---

lgsm/modules/command_update_linuxgsm.sh

prevents caching when in dev-debug mode
Fixes #4528
-   [ ] I have provided a detailed enough description of this PR. …

feat(dev):add nocache if dev-debug is enabled

---

lgsm/modules/core_dl.sh
lgsm/modules/update_mcb.sh

This PR fixes the download url of the minecraft bedrock server. It also includes a workaround for the file download (without useragent it isn't working)
Fixes https://github.com/GameServerManagers/LinuxGSM/issues/4673
-   [X] This pull request subject follows the Conventional Commits standard.
-   [X] I have …

fix(mcbserver): Wrong download url for serverfiles

---

lgsm/modules/info_game.sh
lgsm/modules/update_fctr.sh

Changes the command used to extract the server version to only take the first match so that it ignores the architecture string.
Fixes #4687 
-   [x] I have checked that this code is …

fix(fctrserver): parse updated version string correctly
